### ISSUE TITLE
Enable / Disable button_text click action

### ISSUE THREAD

**Issue by feradelectronics** [maykar/custom-header#102]
Add a switch(way) to enable/disable the button_text click (Open Lovelace menu).  Include it in exceptions for a specific or non admin users?

**Comment by maykar** [comment]
Ah, okay. I misunderstood you on discord a bit. I don't think I'll add a way to disable the button's click action, but you could just hide all the options in that menu for that user. Going to close this one as a duplicate since someone added one for adding admin check already. #101
