### ISSUE TITLE
Custom Header consumes too much space / ignores theme color

### ISSUE THREAD

**Issue by Pe-MaKer** [maykar/custom-header#105]
After migration from CCH to Custom Header I experience some strage behaviour:

1.  The header is too large in height and
2.  Theme color will be ignored on mobile app but shown right on the browser

The following screenshots should explain the issue and show my settings
![Screenshot_20200115-164418_Home Assistant](https://user-images.githubusercontent.com/44093812/72448703-beed7f80-37b7-11ea-96ed-65d9c59421aa.jpg)
![Screenshot_20200115-164857_Home Assistant](https://user-images.githubusercontent.com/44093812/72448714-c4e36080-37b7-11ea-90c1-260d1b92b094.jpg)
![2020-01-15 16_42_51-Home Assistant](https://user-images.githubusercontent.com/44093812/72448757-daf12100-37b7-11ea-8c4f-58f8cef6fa8f.png)

**Comment by maykar** [comment]
You haven't shared your config (please read issues section of docs) but I imagine you still have CCH in your resources

**Comment by maykar** [comment]
Also many options have changed, including custom headers theme vars, be sure to check it out in the docs as well

**Comment by Pe-MaKer** [comment]
> You haven't shared your resources section, but I imagine you still have CCH in your resources

After checking the ressources in the RAW editor, I found and removed any CCH keys. That did the trick.

Thanks a lot mate!
