### ISSUE TITLE
Templating variable: url host

### ISSUE THREAD

**Issue by gadgetchnnel** [maykar/custom-header#109]
It would be useful to have the url hostname (with or without post number) as a template variable, as this would allow templates based on whether we are accessing Home Assistant via the internal or external URL.

For example, there could be two views showing the same camera with one defaulting to the live feed and one defaulting to a still image. The live feed tab could be shown only when using the internal url and the still image tab could be shown on the external url.

**Comment by maykar** [comment]
I think a template var that is just the entire URL should work for this one. That way you can do something like:

`'{% if "nabu.casa" in url %}do something{% endif %}'`

**Comment by maykar** [comment]
This has been added or fixed in the latest version 1.2.2. After updating be sure to check your browser's dev console (usually F12) to make sure you are running the latest version. If it doesn't display 1.2.2 you may either need to clear your cache or reinstall.
