### ISSUE TITLE
Cannot read property 'querySelector'

### ISSUE THREAD

**Issue by condemil** [maykar/custom-header#110]
During home-assistant restart I have the following error:

```
/local/custom-header.js:1:7028 Uncaught TypeError: Cannot read property 'querySelector' of undefined
```

home-assistant version: 0.104.2
custom-header version: 1.2.1

This is my configuration:

```
custom_header:
  compact_mode: true
```

**Comment by maykar** [comment]
Is this still an issue? Does it happen on every restart?
