### ISSUE TITLE
Handle empty header text or add HA title as a template var

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#113]
using a header_text_template works fine. In my use case it is a complex marquee (might not be relevant, but nonetheless).

it is selected with this template:

```
header_text: >-
  {% if is_state('input_boolean.ch_use_header_text_template','on') %}
  {% if is_state('input_boolean.ch_vertical_marquee_up','on') %}
  {% set keyframe = "@keyframes show {
  100% {margin-top:-144px;}
  83% {margin-top:-96px;}
  67% {margin-top:-96px;}
  50% {margin-top:-48px;}
  33% {margin-top:-48px;}
  17% {margin-top:0px;}
  0% {margin-top:0px;}}" %}
  {% else %}
  {% set keyframe = "@keyframes show {
  0% {margin-top:-144px;}
  17% {margin-top:-96px;}
  33% {margin-top:-96px;}
  50% {margin-top:-48px;}
  67% {margin-top:-48px;}
  83% {margin-top:0px;}
  100% {margin-top:0px;}}" %}
  {% endif %}
  <style>
  #flipper{color:#999;}
  #flip {height:24px;overflow:hidden;}
  #flip > div > div {color:var(--primary-text-color);height:24px;margin-bottom:24px;display:inline-block;text-overflow: clip;white-space: nowrap;}
  #flip div:first-child {animation: show 10s linear infinite;}
  {{keyframe}}
  #flipper p {position:fixed;color:#999; }
  </style>
  <div style='float: left'>Ha Rpi4:&nbsp;</div>
  <div id=flip><div><div>
  Summary - {{states('sensor.dark_sky_summary')}}</div></div><div><div>
  Daily - {{states('sensor.dark_sky_daily_summary')}}</div></div><div><div>
  Hourly - {{states('sensor.dark_sky_hourly_summary')}}</div></div><div><div>
  Summary - {{states('sensor.dark_sky_summary')}}</div></div><div><div>
  {% endif %}
```

if the ch_use_header_text_template boolean is turned_off, it would need to show the default header, while at the moment it seems to still show the output off the template, which is empty... 

the test_template reveals that is is in fact empty. Same goes for my footer template I use on mobile, and which is switched on/off using the same boolean:

```
      header_text: >-
        {% if is_state('input_boolean.ch_use_header_text_template','on') %}
        {% set inside=states('sensor.temperatuur_living')%}
        {% set outside=states('sensor.temp_current')%}
        {% set temp_color='var(--primary-text-color)'%}
        {% set symbol='°C' %}
        <div style='display: flex;display: -webkit-flex;'>
        <div>Ha&nbspRpi4:&nbsp;</div>
        <marquee direction={% if is_state('input_boolean.ch_horizontal_marquee_right','on')%} 'right' {% else%}'left' {% endif%} >
        <span style='color: {{temp_color}}'>
        Inside temperature: {{inside}}{{symbol}},
        Outside temperature: {{outside}}{{symbol}},
        </span>
        <span style='color: orange;'>
        System alerts: {{states('sensor.marquee_alerts')}}
        </span>
        <span style='color: {{ temp_color }}'>
        Summary - {{states('sensor.dark_sky_summary')}},
        Daily -  {{states('sensor.dark_sky_daily_summary').split('.')[0]}},
        Hourly - {{states('sensor.dark_sky_hourly_summary').split('.')[0]}}.
        </span>
        </marquee>
        {% endif %}
```

<img width="541" alt="Schermafbeelding 2020-01-22 om 20 55 18" src="https://user-images.githubusercontent.com/33354141/72929096-86bae380-3d59-11ea-9b2d-744e246fb418.png">

this issue was already apparent on 1.2.1, and discussed on the community, but maybe best file an issue here too, now it still is bugging the latest 1.2.3 which I am using obviously.

HA 104.3 Rpi4

**Comment by maykar** [comment]
So, this should be handled by the template itself with an else statement. The only way that I could get this to work in the way you describe would be to detect when header_text is an empty string ("") and replace it with the default. Unfortunately, this would mean that when someone wants it to be an empty string it would always reset to default.

**Comment by Mariusthvdb** [comment]
Well, that’s what I suggested when writing these templates, to always use an else clause....
What do zo need in that case? A hard coded title, or can I reference the default header text?

It’s just that using the same technique on the options text works fine . It the template is disabled it shows the 3 dots.

**Comment by maykar** [comment]
An else statement shouldn't always be required, but it just happens that in this case it makes sense. The default state of the options button is an icon, so that will behave differently. I would hard code the title as it is just static text for now, but expect a template variable to be added just for this in a coming release.

**Comment by maykar** [comment]
Reopening so that I won't forget to do so.

**Comment by Mariusthvdb** [comment]
great!

Ive added the hard-coded else statement for now, but eagerly awaiting your new template variable for that.
thanks!

**Comment by maykar** [comment]
An empty header_text should now result in default text.
