### ISSUE TITLE
Changing theme doesn't change the header/footer color

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/custom-header#115]
HI, 

as of the latest version 1.2.2/3 a theme change doesn't change the color of the header/footer.

It takes a manual refresh to do so. Both on Safari and Chrome desktop and mobile.

ha rpi4 104.3 hassio

no relevant setting in CH config.

**Comment by maykar** [comment]
Should be fixed in latest release

**Comment by Mariusthvdb** [comment]
It is fixed, thanks !
