### ISSUE TITLE
'flickering' between tabs

### ISSUE THREAD

**Issue by aptonline** [maykar/custom-header#119]
Since 1.3.0 I'm experiencing an issue where 'occasionally' my setup flicks from one tab/view to another very quickly on its own and even a refresh doesn't resolve the issue.  Closing the window and reopening does fix it but it can return.

I have disabled custom-header and the issue goes away.  Happens in Safari on macOS 10.14.6 and Safari on iOS/iPadOS 13.3.

Home Assistant 0.104.3
Frontend version: 20200108.2 - latest

**Comment by Krocko** [comment]
I have the same issue. 
This occurs if I am not on the default view and switch to an other entry from the sidebar. If I now switch back to the views, it is flickering between the last opened view and the default view. 
If I am on the default view and switch to an other entry from the sidebar and then switch back to the views, the flickering don‘t happen. 
This is 100% reproducible.

**Comment by maykar** [comment]
Please, share your config or any other info from the link in the bots comment above.

**Comment by Krocko** [comment]
`
custom_header:
  active_tab_color: var(--primary-color)
  background: repeat url('/local/bilder/Header.png')
  default_tab_on_refresh: false
  editor_warnings: false
  notification_dot_color: var(--state-icon-active-color)
  tab_indicator_color: var(--primary-color)
`
Homeassistant 0.104.3
It starts with custom header 1.2.5 I think (the first update from yesterday).

**Comment by aptonline** [comment]
Noting special in my custom header config, just the default install.

**Comment by PostSven** [comment]
@maykar this is the same as i reported in https://github.com/maykar/custom-header/issues/118

**Comment by aptonline** [comment]
Installed 1.3.1 and testing.

**Comment by aptonline** [comment]
Still doing it for me, cleaned cache in iOS app too. See the GIF below.
![6E6B1111-8A16-4A15-9ED0-D8EA06E73CE5](https://user-images.githubusercontent.com/190136/73139511-a4908d00-4066-11ea-9b2b-4c5fa46a9b70.gif)

**Comment by maykar** [comment]
Be sure that the correct version is installed, may need to reinstall via HACS. If you open the dev tools console in Safari it will report the version being used. Make sure it reports 1.3.1

**Comment by Krocko** [comment]
For me it is fixed with v.1.3.1 but i had to reboot HA.

**Comment by aptonline** [comment]
Reboot and reinstall seems to have forced 1.3.1 install enough though I did the upgrade. Will continue to test

**Comment by aptonline** [comment]
Issue seems to be resolved, happy to close the ticket.  Thanks for the quick fix :)
