### ISSUE TITLE
Template not working in exception rule with disabled_mode false

### ISSUE THREAD

**Issue by burnnat** [maykar/custom-header#120]
In my configuration, I have custom_header disabled by default for all users except a select few, that display a clock in header via config like this:

    custom_header:
      disabled_mode: true
      exceptions:
        - conditions:
            user: User
          config:
            disabled_mode: false
            button_text:
              options: '{{ hours12 }}:{{ minutesLZ }} {{ AMPM }}'

Previously this had been working fine, but after updating to the latest version, template replacement has stopped working for those users (the raw template string is shown in the header instead). If I modify the config to enable custom_header for all users, the template replacement starts working again:

    custom_header:
      disabled_mode: false
      exceptions:
        - conditions:
            user: User
          config:
            button_text:
              options: '{{ hours12 }}:{{ minutesLZ }} {{ AMPM }}'
        - conditions:
            user: Other Users
          config:
            disabled_mode: true

However, that's not as convenient since I need to list the other users explicitly. Unfortunately I don't remember what version I was using before the update so I can't say exactly when it broke but it definitely looks like the behavior changed for this case.

**Comment by maykar** [comment]
This was a bug introduced with the template condition in exceptions, should be fixed in latest release.
