### ISSUE TITLE
After updating HA 104.1 to 104.3 with latest CH I get 'custom-header.js:145:62294 TypeError: F(...) is null'

### ISSUE THREAD

**Issue by TheStigh** [maykar/custom-header#122]
Hi,

Running version 1.3.2 of Custom Header installed via HACS. All has been working well and no error messages until I last night updated from 104.1 to 104.3. Now I have this in my log (but not any noticable errors in my header):

`https://xxxxxxxxxx.ui.nabu.casa/community_plugin/custom-header/custom-header.js:145:62294 TypeError: F(...) is null`

Any suggestions on what I can do to resolve this?

**Comment by maykar** [comment]
When does this happen? Have you seen it more than once in your logs?

**Comment by stevenjev** [comment]
I too am seeing this same error: 

    2020-01-31 12:37:35 ERROR (MainThread) [frontend.js.latest.202001082] https://****/community_plugin/custom-header/custom-header.js:145:62294 TypeError: F(...) is null

However, I only see that error if I have a Firefox window open while I wait for the restart. If I close all browser windows and wait for the restart to be complete, and then open, I do not see any errors appear. I also tried to recreate this with a Chrome window open, and I still see an error appear if I leave the browser window open while restarting the HA server. This is the error I see when using Chrome:
    
    2020-01-31 13:08:36 ERROR (MainThread) [frontend.js.latest.202001082] https://****/community_plugin/custom-header/custom-header.js:145:62297 Uncaught TypeError: Cannot read property 'current_view' of null


My config in Lovelace:

    custom_header:
      compact_mode: true

**Comment by TheStigh** [comment]
I downgraded to 104.1 and issue still persist, though appear only after reboot. As @stevenjev mentions, I can confirm that it seems to be related to "if a browser window is open". I had two windows open, one with internal IP, other with nabu.casa URL, then bort appeared as errors in the log.


`

**Comment by vajonam** [comment]
I am seeing this as well, add agree that its related to window being open. This occurs also on the latest beta which is 0.105.0b7

```
https://hass.manojav.com/community_plugin/custom-header/custom-header.js:145:62297 Uncaught TypeError: Cannot read property 'current_view' of null
```

**Comment by maykar** [comment]
I'm aware of it and found the cause, should be fixed in latest release. Shouldn't affect any functionality and will only appear on restart. I'm on it.

**Comment by Pliind** [comment]
i got this error also, and want to check if anybody with this same issue also gets a huge header? I see it going the correct size and then it goes huge after refreshing.

**Comment by maykar** [comment]
Huge header usually means you have both Custom Header and Compact Custom Header installed at the same time

**Comment by Pliind** [comment]
Well look at that.. i did not think of removing the lines in resources, working like a charm now. Thanks!

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by maykar** [comment]
Current latest version as of this comment it 1.3.6, be sure to "show beta" in HACS if you use it as the latest releases have all been pre-releases.
