### ISSUE TITLE
Custom Header Will Not Load on HACS 20.8

### ISSUE THREAD

**Issue by jcqrs** [maykar/custom-header#123]
As the title states, I am trying to install this on HACS 20.8. I've already installed/reinstalled, restarted twice, this will not load. I also keep getting the below file in addition to the primary (.js) one. I deleted this but it comes right back (like a pickle!)

> /config/www/community/custom-header/custom-header.js.gz (file name)
> 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte (file content)

edited for clarification

Thanks in advance.

**Comment by maykar** [comment]
Not seeing this issue on my end, but this would also not be a Custom Header issue. Try uninstalling Custom Header, going back into Lovelace and refreshing with CTRL+SHIFT+R (or just clear cache), then go back into HACS and reinstall. 

If that doesn't do it, add an issue to the HACS repo.
