### ISSUE TITLE
Header text as current View title is not refreshed

### ISSUE THREAD

**Issue by dmatik** [maykar/custom-header#128]
Hi,
I have set the header text to '{{ viewTitle }}'.
However when moving through tabs the text is not changes, only when doing refresh of lovlace or browser.
Is there any way to configure it?

Here is my configuration:

![2020-02-08_13-19-38](https://user-images.githubusercontent.com/5577386/74084225-cb42c080-4a75-11ea-953e-ba550ff95b03.jpg)

Thanks in advance.

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by dmatik** [comment]
> Please try the latest version and report back:
> 
> https://community.home-assistant.io/t/custom-header/155399/636

Hi,
I tried with latest version, I am also on latest 0.107.7 HA version.
Still does not work.
I tried to clean cache.

**Comment by maykar** [comment]
If you open your browser's dev tools (usually F12) can you confirm that you're seeing the latest version reported.

![image](https://user-images.githubusercontent.com/25127328/77850941-ea232080-71a3-11ea-9f39-72ecacb59925.png)

Gif below uses this config with CH v1.3.5:

```
custom_header:
  header_text: '{{viewTitle}}'
```

![tabs](https://user-images.githubusercontent.com/25127328/77850994-4d14b780-71a4-11ea-9730-642b6d4a1a0f.gif)

**Comment by dmatik** [comment]
Hi,
I must be missing here something, but the latest version I see in HACS is 1.3.2, and that is what I see indeed in dev tools console.

**Comment by maykar** [comment]
You need to "show beta" in HACS as the recent updates are pre-releases, should have mentioned it.

![show beta](https://user-images.githubusercontent.com/25127328/77851177-8f8ac400-71a5-11ea-9303-688fd99d9695.gif)

**Comment by dmatik** [comment]
Hi,
Yes, figured it out, installed 1.3.5 and 1.3.6. 
This is issue actually looks fixed, works just fine.
However I am not able to set the split mode, some bug there. Went back to 1.3.2 and it is back working again.

**Comment by maykar** [comment]
I can confirm that at least on my side that split mode is working fine and have had no reports of there being issues with it. If it's not working for you, please create a new issue.

**Comment by dmatik** [comment]
Hi,
Found what was my issue, on 1.3.6 I have to set the compact_mode to false in order to use split mode, which is fine.
In 1.3.2 it was working even with compact_mode as true.

Thank you very much for your support!
