### ISSUE TITLE
Header title not fully showing when active on tab

### ISSUE THREAD

**Issue by iptvcld** [maykar/custom-header#131]
I have my setup to load into a specific tab on mobile upon startup. That works and it goes to the correct tab upon refresh but the tab title is not fully shown as per the image below. It used to always show the full tab name (Summary) 
![Screenshot_20200212-063915](https://user-images.githubusercontent.com/34818686/74333746-8dd87e80-4d66-11ea-80e3-c0fb55a588d2.jpg)

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by iptvcld** [comment]
Thanks, new update is not detecting mobile exception.

**Comment by maykar** [comment]
Create a new issue with the required information, closing this one as I think there are 2 other duplicate issues related to this anyhow.
