### ISSUE TITLE
Navigation Buttons on the left

### ISSUE THREAD

**Issue by jayfbeast** [maykar/custom-header#133]
Good day,

It would be great if there was some kind of a "Left Mode" (exactly like the "Footer Mode", but on the left side).

Pretty much like this:

![Screen Shot 2020-02-16 at 8 27 41 AM](https://user-images.githubusercontent.com/54486962/74618862-7bad6600-5101-11ea-97e4-d7d1041f1dfc.png)

Thank you!

**Comment by maykar** [comment]
This wouldn't work so well unfortunately. It would be a nightmare to support as well as the fact that not everyone uses icons for tabs, meaning the sidebar would end up being very large in some cases. I may reconsider this at some point, but I think header and footer may be the only options.

**Comment by madmicio** [comment]
I'm also interested in having a left sidebar.
for the moment I have used several custom components to obtain it, I hope you can consider developing this option.
thank you
