### ISSUE TITLE
Center Navigation Button

### ISSUE THREAD

**Issue by jayfbeast** [maykar/custom-header#134]
Good day,

right now it is possible to have the Navigation Button either on the left or right side. It would be great to have the ability to center those buttons.

Thank you!

**Comment by maykar** [comment]
With the variation of user configs (number of tabs, etc.), this is one that I won't be adding. This is, however, something that you can adjust with advanced styling options if need be and I discussed a few different options in [this issue](https://github.com/maykar/custom-header/issues/198) (towards the end).

**Comment by maykar** [comment]
With a little bit of work and a new feature, this is now possible. Using the new fit_tabs feature and some custom css on the tab container you can get your tabs centered. You may need to adjust the width to your needs, doesn't need to be a percent either can use pixel sized width as well:

With percent:
```
  fit_tabs: true
  tab_container_css: 'width: 50% !important; margin: auto !important;'
```

With pixels:
```
  fit_tabs: true
  tab_container_css: 'width: 400px !important; margin: auto !important;'
```
