### ISSUE TITLE
After 1 exception, no other exceptions are processed

### ISSUE THREAD

**Issue by suprphrk** [maykar/custom-header#137]
I have two exceptions set.  One for a Harmony remote that is set to Kiosk mode with everything hidden.  Its username is "remote" and that exception holds.  However, I set up a wall switch panel in the dining room and its username is "diningroom".  I'm currently logged in as "diningroom" in this screen shot, and you can see that it's set correctly and saves correctly, but I still have the header, sidebar, it's not in Kiosk mode, and it doesn't auto-redirect to tab 6.

Custom Header v1.3.2
Home Assistant Core v0.105.4

Configuration: (edit - Quote, Code, or plain text wasn't showing up correctly)

![image](https://user-images.githubusercontent.com/3477773/75043289-6cbe0f00-5485-11ea-81f6-51c6cf252c05.png)

![image](https://user-images.githubusercontent.com/3477773/75042562-35029780-5484-11ea-904b-27a081da2107.png)

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by gadgetchnnel** [comment]
The documentation on exceptions [here](https://maykar.github.io/custom-header/#configuration/exceptions) describes **user** as:

> A user or a comma separated list of multiple users. This is the Home Assistant user's name, **not username** (if they're different) or an user's ID.

It looks like, from the screenshot, that the user's name is "Dining Room" while the exception in the config has it as "diningroom".

**Comment by maykar** [comment]
@gadgetchnnel Good catch, thanks. 

@suprphrk It should be `user: Dining Room` not `user: diningroom`.
