### ISSUE TITLE
Give the possibility to enable/disable click on a tab

### ISSUE THREAD

**Issue by albertorivi** [maykar/custom-header#140]
It would be great if for each single tab inside the custom header could be an option in order to enable or disable the click on the tabs, in order to use it as only label (maybe for a possible group).

**Comment by maykar** [comment]
This won't really be a feature I will be adding, but it is already possible using [advanced styling](https://maykar.github.io/custom-header/#styling/advanced) like this:

```
custom_header:
  tabs_css:
    7:  'pointer-events:none;'
```
