### ISSUE TITLE
Custom header image keeps spanning

### ISSUE THREAD

**Issue by iptvcld** [maykar/custom-header#146]
Hello;
I have a custom image for the header and when i view HA on a large monitor, the header image keeps repeating it self (attached screenshot) im sure will help explain.
Thanks,
![11q](https://user-images.githubusercontent.com/34818686/76525671-a8c01080-6442-11ea-8936-4bce8c9226b5.PNG)

**Comment by maykar** [comment]
You haven't provided the required information (see comment above), so I haven't seen your config. I am going to assume that the css you are using for the background doesn't include `no-repeat`.

The [readme for the background property](https://maykar.github.io/custom-header/#styling/styling) has a link that explains how to use background css. Here is an example of what you're probably looking for:

`background: no-repeat left center url('images/star.png')`

**Comment by iptvcld** [comment]
after posting; i added the no-repeat and when i did that - the background now was not going all the way (i guess it was too small).  I assume you cannot use a background that has text as it will always span that across if lets say you are viewing your frontend on a TV screen.

**Comment by maykar** [comment]
There are 2 solutions to that:
* Make a very wide image (as wide as the highest resolution it would be viewed at)
* Make the background color the same color as the images background (example below)

`background: "no-repeat left center #89d7fd url('images/star.png')"`

The color used in the example above is sampled from your screenshot `#89d7fd`

**Comment by iptvcld** [comment]
Thank you!! this worked...
`background: "no-repeat #89d7fd url('/local/backgrounds/53.png')"`

**Comment by iptvcld** [comment]
thanks again for your help!
