### ISSUE TITLE
Errors with duckdns after restart of HA

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#152]
Issue:
From time to time i got these errors after a restart

## Environment

- Home Assistant release with the issue: 107.7
- Last working Home Assistant release (if known): ?? 104.x
- Operating environment (Hass.io/Docker/Windows/etc.): hassio
- Integration causing this issue: Custom Header
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt
Logger: frontend.js.latest.202003181
Source: components/system_log/__init__.py:209
First occurred: 10:47:27 (2 occurrences)
Last logged: 10:47:27

https://nauen.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:1:7166 Uncaught TypeError: Cannot read property 'querySelector' of undefined
https://nauen.duckdns.org:8123/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null

```

## Additional information

**Comment by maykar** [comment]
Please try the latest version and report back:

https://community.home-assistant.io/t/custom-header/155399/636

**Comment by Pirol62** [comment]
I updated to 107.7 on friday. Haven't had this error again so far.
And there were a lot of restarts ;-)
I will watch this and may reopen.
Thanks

**Comment by maykar** [comment]
You may see the one for swipe-navigation again as it hasn't been updated for 0.1.07+ yet, but should be soon.
