### ISSUE TITLE
'Menu in Dropdown menu' works only when 'Disable Sidebar' is turned off

### ISSUE THREAD

**Issue by shevu** [maykar/custom-header#160]
If 'Disable Sidebar' option is turned on then 'Menu' from dropdown menu disappear. Couple of versions ago it worked properly.

Browser: Chrome
HA version: 0.107.7
Custom header version: 1.3.8

**Comment by maykar** [comment]
["disable_sidebar...Disables and hides the sidebar and menu button"](https://maykar.github.io/custom-header/#configuration/main)

If it was appearing when disable sidebar was on, then it was a bug. The menu button is only used for the sidebar and as such is disabled with it.
