### ISSUE TITLE
Time with seconds

### ISSUE THREAD

**Issue by ranrinc** [maykar/custom-header#161]
Is there a possibility of having to show time with seconds? Currently it only show hours and minutes.. Thanks

**Comment by maykar** [comment]
I may revisit this at some point, but right now the clock is tied to the rendering of templates (happens once a minute and on each state change if the state is used in a template). Changing this to happen every second would slow the interface to a crawl. The other option would to be to make a clock module that would be dropped into templates where it is used, but this might just be more trouble than its worth. Closing for now, but I'm considering it.
