### ISSUE TITLE
Slow with HA 107

### ISSUE THREAD

**Issue by Benjy04** [maykar/custom-header#163]
Since the update to Home Assistanr V107 the navbar does load very slow and sometimes it doesn't show the right navbar. I use Dwains Theme and since the update the navbar is very buggy.

**Comment by maykar** [comment]
On every device or just certain ones, which browsers, which devices, what's your config, do you get any errors in the HA logs, any errors in your browser's console?

I can't troubleshoot or track down issues with no information. Follow the link from the bot's comment above and provide as much information from that page and my questions above as possible and then reopen the issue.

**Comment by Benjy04** [comment]
Sorry,
there is no error in the ha log or the browser console with your integration.
The Error appears on every device and every browser (edge chromium excluded, here it works most of the time).

I have problems with your integration sice upgrading to HA 107.

**Comment by maykar** [comment]
and your config would be?

**Comment by Benjy04** [comment]
Heres the config which the theme use: https://pastebin.com/VxdatVqk

**Comment by Benjy04** [comment]
I use Firefox, Edge Chromium and the Android HA App

**Comment by maykar** [comment]
Much has changed recently, the current version is 1.4.5. Is this still an issue?
