### ISSUE TITLE
Error in HA logs ` TypeError: Argument 1 of Node.appendChild is not an object`

### ISSUE THREAD

**Issue by mdegat01** [maykar/custom-header#166]
I saw this error in my logs this morning related to the custom header component.
>2020-04-10 23:45:34 ERROR (MainThread) [frontend.js.latest.202004072] {HA Address}/hacsfiles/custom-header/custom-header.js:1:15191 TypeError: Argument 1 of Node.appendChild is not an object.

I only have exactly one log entry of this, its not occurring repeatedly or anything. But wanted to report it since its a JS error and I don't really know exactly what causes it. 

I don't really have any other info about it unfortunately, I can't remember what exactly I was doing at 11:45PM last night with HA. I was definitely using and editing the UI and I do use custom-header but I don't know what specific action triggered the one instance of this log.

My HA version is 0.108.3 and my custom-header version is 1.3.8.

**Comment by ranrinc** [comment]
I believe my hass also showing this error

**Comment by usInagaZs** [comment]
Same here.

**Comment by maykar** [comment]
Much has changed recently, the current version is 1.4.5. Is this still an issue?

**Comment by ranrinc** [comment]
again this issue is resolve.. thanks man
