### ISSUE TITLE
Bad locale broke lovelace editing

### ISSUE THREAD

**Issue by phd59** [maykar/custom-header#169]
(I am newbie, sorry if this in not in the right place)

I wanted to edit title , and entered fr_FR.uf8 as locale (old linux use).
Since, title went down the screen and becomes uneditable (i worked in UI mode).

Tried to uninstall/reinstall custom-header, useless, it doesnt forgets my bad configuration.

I would like to know where is stored that data, so that I could remove or correct it

thanks by advance

**Comment by phd59** [comment]
Home assistant 0.108.3
custom-header 1.3.8

In home assistant log :
http://192.168.1.47:8123/hacsfiles/custom-header/custom-header.js:1:18678 RangeError: invalid language tag: "fr_FR.UTF8"
14:04:14 – components/system_log/__init__.py (ERROR) - message survenu pour la première fois à 11:48:36 et apparu 2 fois.

**Comment by maykar** [comment]
Remove it using the [raw config editor](https://maykar.github.io/custom-header/#configuration/config)

**Comment by phd59** [comment]
Sorry, but as the title bar is broken, it is also impossible to access the raw config editor from UI.
The only solution I found is switching to yaml mode, but doing that I lose all the existing UI config...

**Comment by phd59** [comment]
Fixed.
Got source yaml for each card, that was still possible, then switched to yaml mode and pasted yaml to ui-lovelace.yaml.

Thanks for answer and for your add-on

**Comment by maykar** [comment]
If you ever need to disable CH follow the first two important notes [here](https://maykar.github.io/custom-header/#intro/notes)
