### ISSUE TITLE
CCH and lovelace dashboards

### ISSUE THREAD

**Issue by isgoet** [maykar/custom-header#171]
with the update of HA and the possibility to have lovelace dashboards the CCH is not working correctly.
when start then the default dashboard is shown correctly and CCH works.
But when in the sidebar switch to another lovelace dashboard then CCH is not loaded automaticly.
Only after refresh the page then CCH is loaded and working.
And with the HA app the function to swipe down and refresh the page is not possible so CCH is not loading and functioning....only in the default dashboard and no other dashboards that has been set up.

**Comment by pkishino** [comment]
Hmm, I can swipe down in the app (iOS) and refresh, but for me custom header works fine for the other dashboards I created, no need to refresh.

**Comment by maykar** [comment]
Not enough info, please read the issues section (from the bots comment above) and provide as much information as you can and then reopen. Would also like to know what browser this is happening in and if it's working in some browsers and not others.

**Comment by Villhellm** [comment]
It seems if you load in (refresh browser page) on a dashboard that doesn't have a custom header configuration and switch to one that does or if you load in to one that does, switch to one that doesn't, and switch back to the first it will not load the custom header again until the page is refreshed or switch views if there is more than one view configured.

Here is the configuration on the dashboard that has one
```yaml
custom_header:
  compact_mode: true
  background: transparent
```

This is on Chrome 81.0.4044.129
It appears Safari on phone and desktop does not experience this issue.

**Comment by maykar** [comment]
CH config should be placed in whatever dashboard you want to use it in.

**Comment by Villhellm** [comment]
I know multiple dashboards is still a relatively new concept, but you might want to rethink that logic in the future. Checking for a configuration before fully loading a plugin seems like the most complete way to allow users to tweak their setup exactly the way they want. It's both a good and bad thing imo that the powers that be decided to share resources between dashboards, but for now it's up to the plugin devs to handle that. 

The hass object has a panelUrl property that updates if dashboards are switched (or if the user goes into configuration/hacs/dev-tools/etc). Checking for the lovelace object and subsequently a plugin configuration after the panelUrl property changes state is the best way that I've found so far to handle this.

**Comment by maykar** [comment]
I didn't make the decision for it to function that way at the time, I was more focused on the fact that dashboards broke CH. The last time I had time to work on this project was to update it to function with dashboards and even then it was 2 weeks after the HA update when I was able to release it. I have even [less time now](https://community.home-assistant.io/t/custom-header/155399/695). I am always open to pull requests.

Ideally CH should just default to `disabled: true` if there is no CH config

**Comment by Villhellm** [comment]
Oh please don't think I'm trying to be overly critical, I didn't mean to overwhelm you even more than you are (apologies, I was not aware of that forum post).

I'll try to set up a dev environment for CH and work on a pull request to fine tune function with dashboards/raw config editing.
