### ISSUE TITLE
Buil-in VAR for the Home Assistant version running on the system

### ISSUE THREAD

**Issue by dede34fr** [maykar/custom-header#172]
Hi, would it be possible to have a new buil-in var for the current HA version running on the system?
Would love adding that to the title bar (button text, options).
Tks

**Comment by maykar** [comment]
`{{ hassVersion }}` template variable added in 1.4.6

**Comment by dede34fr** [comment]
Tks a lot

**Comment by dede34fr** [comment]
Hi Ryan,
please update doc accordingly for that {{ hassVersion }}
https://maykar.github.io/custom-header/#templates/builtin

Implemented! Tks

Denis

**Comment by maykar** [comment]
That's the next thing on my list, docs need a fair few updates.

**Comment by maykar** [comment]
There is an edit link on each page of the docs as well so anyone can submit and update to be pulled.
