### ISSUE TITLE
This component has been blacklisted on HACS

### ISSUE THREAD

**Issue by mdegat01** [maykar/custom-header#173]
I really like this component and would like to keep using it but I am concerned because it was blacklisted.  The blacklist is [here](https://github.com/hacs/default/blob/master/blacklist). Would like to see it removed from the blacklist and listed in HACS again.

**Comment by maykar** [comment]
Compact Custom Header was blacklisted by me since it was replaced by Custom Header

**Comment by mdegat01** [comment]
Right, sorry about that, I read it wrong in the list.  Missed the compact part.
