### ISSUE TITLE
Error caused by mobile apps

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#176]
The most time I use different mobile devices with HA Companion app.
I'm getting these errors:
````
Protokolldetails ( ERROR )
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 26. April 2020, 9:57:01 (125 occurrences)
Last logged: 8:25:07

https://i0gyzxe3ihswk7c828fvjz6uss4qm87c.ui.nabu.casa/hacsfiles/custom-header/custom-header.js:603:15224 Uncaught TypeError: Cannot read property 'setAttribute' of null
https://nauen.duckdns.org:8123/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:34:36 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
https://nauen.duckdns.org:8123/frontend_latest/chunk.ee220cc88bc60d4bc620.js:2893:1667 Uncaught TypeError: Cannot convert undefined or null to object
````
I'm on 108.8 but had that error with 107.x as well.
HACS: 0.24.2
CH: 1.3.8
newest swipe navigation

**Comment by migo-dev** [comment]
Man! Take your urls out of there or are they fake?
I have the same warnings btw.

**Comment by maykar** [comment]
Swipe Navigation has yet to be updated for newer HA versions. I will get back to work on it soon, but it is mostly in a non working state. This is also not the place for issues related to Swipe Navigation, that page is [here](https://github.com/maykar/lovelace-swipe-navigation).

As far as the Custom Header error: Much has changed recently, the current version is 1.4.5. Do you still get the error?

**Comment by Pirol62** [comment]
No, not since 24 hours. Thanks
