### ISSUE TITLE
Custom-header doesn't work with HA 0.110 (dev)

### ISSUE THREAD

**Issue by ualex73** [maykar/custom-header#179]
I am testing with Home Assistant 0.110, which is in development at this moment.

The frontend isn't loading anymore, and i see the following "custom-header" error in my logging:

`2020-05-11 09:42:26 ERROR (MainThread) [frontend.js.latest.202005090] https://hostname/hacsfiles/custom-header/custom-header.js?v=1.3.8:1:16344 Uncaught TypeError: Cannot read property 'style' of null`

**Comment by grantclem** [comment]
Can confirm the issue still in Beta;

`2020-05-14 06:27:15 ERROR (MainThread) [frontend.js.latest.202005130] https://toowong.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null`

`2020-05-14 06:30:22 ERROR (MainThread) [frontend.js.latest.202005130] https://toowong.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:1:13253 TypeError: null is not an object (evaluating 'e.sidebar.main.querySelector')`

`2020-05-14 07:22:17 ERROR (MainThread) [frontend.js.latest.202005130] https://toowong.duckdns.org:8123/hacsfiles/custom-header/custom-header.js:1:16344 TypeError: null is not an object (evaluating 'o[e].querySelector("paper-icon-button").style')`

**Comment by jesserockz** [comment]
https://github.com/maykar/custom-header/blob/9105456fbbe3d77f1aa2a7b335fc0bc9460a9e09/src/build-header.js#L104

Looks like the element has changed to `ha-icon-button` with the mdi-split

https://github.com/home-assistant/frontend/commit/0a92c28bac80a0bddc3f54577fc62670f3974c15#diff-873f41cce3df4d28dd685519a4e87d01L135

**Comment by noxhirsch** [comment]
@jesserockz: Good catch! Replacing all (13) `paper-icon-button` with `ha-icon-button` helped 👍

**Comment by roblamoreaux** [comment]
I also had to change all the 'iron-icon' entries to 'ha-icon' to get it to work again.

**Comment by DavidFW1960** [comment]
> @jesserockz: Good catch! Replacing all (13) `paper-icon-button` with `ha-icon-button` helped 👍

but the hamburger icon to open the side panel doesn't work when I edit the js file..

**Comment by davide-rhw** [comment]
not work with ha 110.0

**Comment by tuga49** [comment]
Im facing the same issue, but with this error on log:

> ERROR (MainThread) [frontend.js.latest.202005190] [MYIP]/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null

**Comment by johnjoemorgan** [comment]
Same here - tried on clean Chrome/Firefox/Edge

2020-05-20 21:08:10 ERROR (MainThread) [frontend.js.latest.202005190] http://IP:8123/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null

**Comment by valderaplets** [comment]
* change all the 'iron-icon' entries to 'ha-icon'  
* Replacing all (13) paper-icon-button with ha-icon-button

works for me.

But I lost the custom color of the active icon.

**Comment by austwhite** [comment]
It took me a little while to work out which custom component was causign this, and it does seem to be the Custom Header component.
The tabs and page header completely disappear on any lovelace tabs/dashboards when using Custom Header.
I had to uninstall this as I wanted some of the additional features in 0.110 (in particular the new ZWave component).
I just wanted to watch this for an update or fix.  0.109.x works fine, this issue only occurs on 0.110.x

**Comment by mpeterson** [comment]
The changes that @valderaplets summarized worked. There is another side effect for me still. I have:

```
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
```

and the clock appears below the header itself

<img width="106" alt="image" src="https://user-images.githubusercontent.com/11870/82454207-25621180-9aba-11ea-8ea0-b3998bec3b79.png">

**Comment by valderaplets** [comment]
>     * change all the 'iron-icon' entries to 'ha-icon'
> 
>     * Replacing all (13) paper-icon-button with ha-icon-button
> 
> 
> works for me.
> 
> But I lost the custom color of the active icon.

This works yes, but the hamburger icon to open the side panel doesn't work when I edit the js file like @DavidFW1960  in phone

**Comment by Sooty70** [comment]
Using custom header and also just upgraded to .110.  The page header has completely disapeared and I've lost the ability to select different Lovelace UI tabs plus edit and update cards...

**Comment by sstratoti** [comment]
Add ?disable_ch to the end of the url to turn off the custom header temporarily. 
However, once I do that I don't see the config option for custom header under the edit menu at the top right.

**Comment by Sooty70** [comment]
Thanks @sstratoti.  I have my tabs back and can edit - but like you say, I don't have the config option in the edit menu...

**Comment by dartfrogdk** [comment]
@Sooty70 I copy that, no edit button, I think it is in Kiosk mode, but how to disable it?

**Comment by bcmitri** [comment]
Once you have it disabled, you should be able to access the menu to access the Raw configuration editor.

Personally, I've elected to copy my config for the Customer Header (should be right at the top of the file) to a text file, then just delete it and uninstall the Custom Header plugin until this issue is fixed.

**Comment by Scope666** [comment]
I restored a Snapshot for 0.109.6, I can't live without Custom Header ... it should honestly be the stock look of the UI.

I'll try again once CH has been updated for 0.110.

**Comment by pironic** [comment]
can confirm, running HACore v0.110.0, CardMod v1.1.0, and CH v1.3.8 it defaults to kiosk mode. This only happens on the default lovelace panel. I have a second ha dashboard that is not affected this way. Completely removing CH from my raw config on the default does not repair it. ?disable_ch is my only option at the moment. 
![image](https://user-images.githubusercontent.com/541154/82480616-4bbf8700-9a91-11ea-84e0-441672cd9075.png)
![image](https://user-images.githubusercontent.com/541154/82480678-6134b100-9a91-11ea-9fd2-530753ea657a.png)

**Comment by rcxrbt** [comment]
Same issue, unistalled Chustom-Header. I m waiting.

**Comment by niemyjski** [comment]
@maykar I can't install the tagged draft release for some reason in has and master doesn't work either.

**Comment by jesserockz** [comment]
@maykar 1.3.9 is all working for me. Manually downloaded [custom-header.js](https://github.com/maykar/custom-header/releases/download/1.3.9/custom-header.js) from the [release](https://github.com/maykar/custom-header/releases/1.3.9) and copied over the one at `/config/www/community/custom-header/custom-header.js`

**Comment by maykar** [comment]
It's labeled as a pre-release so you need to "show beta" in HACS

**Comment by kdvlr** [comment]
Just installed 1.3.9, I got my header bar back, but additional customization such as the time now comes in the next line. See screenshot below

[https://imgur.com/A8lZGzw]

**Comment by roblamoreaux** [comment]
Date and time are below the header for me as well.

**Comment by theone11** [comment]
> It's labeled as a pre-release so you need to "show beta" in HACS

How do I "show beta"?

**Comment by pergolafabio** [comment]
yeah, in top right , but seems the icon is missing there

**Comment by theone11** [comment]
I manually downloaded 1.3.9 and removed the gz file as stated above - HACS still shows 1.3.8 and custom header still not showing at all (I also tried clearing the browser window)

**Comment by pergolafabio** [comment]
i have now this with 1.3.9 : 

`/hacsfiles/custom-header/custom-header.js:596:28156 Uncaught TypeError: Cannot read property 'lovelace' of null`

**Comment by luisiam** [comment]
> > It's labeled as a pre-release so you need to "show beta" in HACS
> 
> How do I "show beta"?

You will have to edit hacs.repositories under /config/.storge. Find the corresponding customer header repository and set show_beta to true.

![image](https://user-images.githubusercontent.com/16310467/82496319-613cad00-9aa1-11ea-9477-113067fe8e08.png)

**Comment by maykar** [comment]
I have released a full release, 1.4.0 as showing beta's isn't as easy as it was previously in HACS. This release addresses the misplaced button text. 

Do not post additional issues here, make a new issue [providing the required info](https://maykar.github.io/custom-header/#issues)

**Comment by maykar** [comment]
@pergolafabio already fixed for next release, it's just an annoying error ATM, but I don't want to post a full release for just that fix.

**Comment by pergolafabio** [comment]
perfect :)

**Comment by marcelliotnet** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍
