### ISSUE TITLE
Header disappears with 0.110.0

### ISSUE THREAD

**Issue by phillprice** [maykar/custom-header#183]
Whole header is invisible with 0.110.0
_Will update with my config after reverting HA to 0.109.6_

Expected:
![Overview_-_Home_Assistant](https://user-images.githubusercontent.com/320214/82441847-79f39580-9a96-11ea-94f2-6f6da439d2bd.png)

Actual:
![Overview_-_Home_Assistant](https://user-images.githubusercontent.com/320214/82440865-ecfc0c80-9a94-11ea-94a0-ff64bdabec46.png)

HA: 0.110.0
Custom Header: 1.3.8
Browser: Firefox 76 on MacOS Sierra (whatismybrowser.com/w/R7TQ82H)

Config: 
```
custom_header:
  compact_mode: true
```

**Comment by rgruyters** [comment]
Duplicate #182

**Comment by phillprice** [comment]
Thanks for linking it, sorry I didn't search content only titles. I've downgraded and I'm happy to test any fixes you have, if you wish :)
