### ISSUE TITLE
TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by jimz011** [maykar/custom-header#185]
```
https://MYDOMAIN/hacsfiles/custom-header/custom-header.js:603:22881 Uncaught TypeError: Cannot read property 'style' of null
11:14:25 PM – components/system_log/__init__.py (ERROR) - message first occurred at 11:13:30 PM and shows up 8 time
```

The error seems different than the last one as it has a different number. The other errors are gone though. Not sure if I had to open up a new one (as you asked for that) or to post it in the running thread.

**Comment by LEJOUI** [comment]
I’m getting this error in 0.39 and 0.40 

`https://cxxx.duckdns.org/hacsfiles/custom-header/custom-header.js:596:55148 TypeError: null is not an object (near '...ha-panel-lovelace").lovelace,!t)return;...')`

**Comment by pasleto** [comment]
Error on my site on 1.4.0:
`Uncaught TypeError: Cannot read property 'lovelace' of null
    at Function.buildConfig (custom-header.js:596)
    at MutationObserver.<anonymous> (custom-header.js:596)`

**Comment by maykar** [comment]
Don't add issues to other issues, especially ones that are completely different than the original issue and always provide the required info from the bots comment. Issue title's should be more specific to prevent this sort of thing.

The error that both @LEJOUI and @pasleto  are referring to is already known and is fixed for the next release. [See this post.](https://community.home-assistant.io/t/custom-header/155399/767)

**Comment by maykar** [comment]
@jimz011  can you click on the `custom-header.js:603:22881` and give me a screenshot of the surrounding code?

**Comment by jimz011** [comment]
Hm, after some crazy stuff (HACS wouldn't install 1.4.0 and just reinstall 1.3.8 again) I managed to get it installed. It seems I can not reproduce this anymore. 

I only have this error left ```custom-header.js:596:28605 Uncaught TypeError: Cannot read property 'lovelace' of null```, but I believe this is already an open issue.

I don't know if both of these issues have to do something with Custom Header not loading on other dashboards (unless I go there from the main dashboard via a button). It seems like it isn't loading custom-header unless I am at the main (default) dashboard. And even if I go to that dashboard, I will have to go to another dashboard first before Custom Header gets loaded. I had initially thought that these errors might be the culprit.
