### ISSUE TITLE
Header completely missing after upgrading to HA 0.110.0

### ISSUE THREAD

**Issue by nickdos** [maykar/custom-header#187]
Running version 1.4.1 of this plugin (I updated the plugin after upgrading to HA 0.110.0).

My "Overview" tab (Lovelace) no longer show the header bar at all and I'm unable to make changes to Lovelace as a result. See screenshot:

![image](https://user-images.githubusercontent.com/532845/82506999-7ae30080-9b44-11ea-97cf-e3f47d8789c9.png)

Uninstalling the plugin and then re-installing again, resolved the issue.

Feel free to close this issue if its considered a one-off upgrade glitch.

**Comment by maykar** [comment]
Probably just a cache issue, but will keep an eye out

**Comment by bakko65** [comment]
same problem, after using disable_ch the view is back

**Comment by JensVanhooydonck** [comment]
Same error:

```
Uncaught TypeError: Cannot read property 'style' of null
    at CustomHeader.cloneButton (custom-header.js:1)
    at CustomHeader.buildHeader (custom-header.js:1)
    at new CustomHeader (custom-header.js:1)
    at custom-header.js:603```

**Comment by photinus** [comment]
Seeing this issue as well after upgrading to custom_header 1.4.3 and Home Assistant 0.110.1

```
Uncaught TypeError: Cannot read property 'setAttribute' of undefined
    at CustomHeader.buildHeader (custom-header.js:1)
    at new CustomHeader (custom-header.js:1)
    at rebuild (custom-header.js:596)
    at custom-header.js:596
```

**Comment by JensVanhooydonck** [comment]
Ctrl +f5 solved it for me after upgrading both

**Comment by bakko65** [comment]
Clearing cache helped for me.
Thanks.
