### ISSUE TITLE
Entering UI edit mode breaks view

### ISSUE THREAD

**Issue by andriej** [maykar/custom-header#189]
Entering 'edit UI' mode with custom header breaks the view and make editing underlaying cards not possible as can be seen on screen:
![image](https://user-images.githubusercontent.com/6303489/82544802-f39e8880-9b55-11ea-993e-d46716fc2a6c.png)
There are cards and badges underneath.

version: 1.4.1

**Comment by mobilemutex** [comment]
Related to this, if you enter 'edit UI' mode, switch to another panel, such as "Supervisor", and then switch back, the header is now gone and you cannot switch pages or exit 'edit ui' mode without reloading the page.

**Comment by maykar** [comment]
Thanks, on it. Both issues should be fixed in next release.

**Comment by mbonaccors** [comment]
Yeah, since i installed the new Hass.io Core & OS / Supervisor updates this week Custom-Header won't even load anymore.. do you have any idea if I would need to remove it completely and reinstall? Or will this be fixed from the update?

**Comment by mbonaccors** [comment]
Yes, this issue is fixed for me now as well - thank you very much maykar! Have a terrific weekend.

**Comment by andriej** [comment]
Sovled :) thx!
