### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by lancer73** [maykar/custom-header#191]
After updating to the latest version, the complete page header and tab bar are gone.

Logs:
ogger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209 
First occurred: 21:20:40 (22 occurrences) 
Last logged: 21:27:48

https://www.gloudemans.info:8123/hacsfiles/custom-header/custom-header.js:1:15443 TypeError: undefined is not an object (evaluating 'e.voice.setAttribute')
https://www.gloudemans.info:8123/frontend_latest/chunk.5ef968208258097f0ba7.js:2:20625 TypeError: undefined is not an object (evaluating 't._leaflet_pos')
https://www.gloudemans.info:8123/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:10:20 TypeError: null is not an object (evaluating 'root.lovelace')

Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209 
First occurred: 21:19:08 (5 occurrences) 
Last logged: 21:19:25

https://www.gloudemans.info:8123/hacsfiles/custom-header/custom-header.js:596:55148 TypeError: null is not an object (near '...ha-panel-lovelace").lovelace,!t)return;...')
https://www.gloudemans.info:8123/hacsfiles/frontend-20200521162326.js:1:17191 NotSupportedError: Cannot define multiple custom elements with the same tag name

HA 0.110.1
Plugin 1.4.3
HACS 1.0

**Comment by userMak** [comment]
Same here with the same setup

**Comment by juan11perez** [comment]
same problem

**Comment by beliy1985** [comment]
again all broke

**Comment by sringaci** [comment]
Same issue. My page header and tab bar are gone. 
HA 0.110.1
Plugin 1.4.3
HACS 1.0

**Comment by jazbraz** [comment]
Same issue. My page header and tab bar are gone.
HA 0.110.1
Plugin 1.4.3
HACS 1.0

**Comment by DanielPiccoli** [comment]
all hell broke loose, lost all my menu

**Comment by tteck** [comment]
> all hell broke loose, lost all my menu - reverted back to 1.3.8 menu is shown again -
> DOWNGRADE from 1.4.3 guys.

Can't do with the new HACS

**Comment by beliy1985** [comment]
> > весь ад вырвался на свободу, потерял все мое меню - вернулся обратно в 1.3.8, меню снова отображается - 
> > DOWNGRADE от 1.4.3 парней.
> 
> Не могу сделать с новым HACS

same problem

**Comment by afxefx** [comment]
If your issue is like mine then it's because you have `conversation:` commented out in your HA configuration.yaml. Unquoting it resolves this error for now but I'm sure maykar will address it properly when time permits. You can add `voice_hide: true` to your CH config to hide the icon for now.

**Comment by CorneliousJD** [comment]
> If your issue is like mine then it's because you have `conversation:` commented out in your HA configuration.yaml. Unquoting it resolves this error for now but I'm sure maykar will address it properly when time permits. You can add `voice_hide: true` to your CH config to hide the icon for now.

Thank you, adding `conversation:` into my HA configuration.yaml allows customer header to come back!

Where is the file for the CH config to add `voice_hide: true` at? No rush, just happy to have tablets on walls working again right now.

**Comment by afxefx** [comment]
Either raw configuration editor or yaml depending on which way you set it up.  Same place you defined all other CH options.

**Comment by CorneliousJD** [comment]
> Either raw configuration editor or yaml depending on which way you set it up. Same place you defined all other CH options.

Hmmm, I just have done it all via the web UI -- I just use it to slim down the header across the board and that's it. I don't see a way via web UI to add anything other than exceptions?

![image](https://user-images.githubusercontent.com/724777/82601540-b64df100-9b7d-11ea-822c-61d88496c00c.png)

**Comment by afxefx** [comment]
Hide Voice Button toggle should do it.

**Comment by stibe881** [comment]
@CorneliousJD 

![453FE18E-D479-445A-ABB5-D08EE9EE953C](https://user-images.githubusercontent.com/24219649/82601885-83712080-9bb0-11ea-9d96-df302a134f27.jpeg)

**Comment by beliy1985** [comment]
> web UI

how to come on web UI?

**Comment by userMak** [comment]
@beliy1985 

add conversation: 
into my HA configuration.yaml allows customer header to come back!

**Comment by beliy1985** [comment]
> > Либо необработанный редактор конфигурации, либо yaml, в зависимости от того, как вы его настроили. Там же, где вы определили все остальные параметры CH.
> 
> Хммм, я только что сделал все это через веб-интерфейс - я просто использую это, чтобы уменьшить заголовок по всем направлениям и все. Я не вижу способ через веб-интерфейс добавить что-либо, кроме исключений?
> 
> ![образ](https://user-images.githubusercontent.com/724777/82601540-b64df100-9b7d-11ea-822c-61d88496c00c.png)

How to enter such settings

**Comment by cjramseyer** [comment]
Same config as everyone else.  Updated to 0.110.1 today.  Everything else is completely updated.  Running on rPi 3B+
Adding conversation: to configuration.yaml restore to header.  Please fix.  Have no need to the conversation integration.

**Comment by lancer73** [comment]
This got fixed so fast I didn’t even notice it.

Thanks!

**Comment by DanielPiccoli** [comment]
> > all hell broke loose, lost all my menu - reverted back to 1.3.8 menu is shown again -
> > DOWNGRADE from 1.4.3 guys.
> 
> Can't do with the new HACS

yes you can - simply click on reinstall on the 3dot icon, then choose a different version.
