### ISSUE TITLE
Latest install (1.4.4) causes issues with HA Mobile App

### ISSUE THREAD

**Issue by sparment** [maykar/custom-header#195]
I just installed version 1.4.4 and am having issues with the HA Mobile App now. Clicking on the Hamburger button within the HA Mobile App does nothing when Custom-Header is loaded in my config file. If I do not load Custom-Header on a reboot, the mobile app works as it should. This is even with commenting out the Custom Header settings in the ui-lovelace.yaml file.

Here is my config:
lovelace:
  mode: yaml
  resources:
   - url: /local/plugins/custom-header.js?v=1.4.4
     type: module

**Comment by luisiam** [comment]
I noticed that as well. Current workaround is to swipe from the edge to reveal the menu.

**Comment by jes1417** [comment]
@luisiam this is very difficult to do with Google's gesture control..

**Comment by dlo747** [comment]
Same here. 1.4.4 menu button doesn’t work on app or mobile site

**Comment by luisiam** [comment]
@jes1417 glad that I am on iOS and the gesture works reasonably well

**Comment by jes1417** [comment]
I got it figured out, Google's gesture control use that motion to go back but if you swipe slightly down while pulling off the edge of the screen the side drawer opens reliably.

**Comment by sparment** [comment]
Agreed, the gesture on the iOS app does the trick.

**Comment by RomRider** [comment]
Why did you close the issue @sparment, it's not solved.

**Comment by bcmitri** [comment]
So, wait....  Is the intent just to live with a work-around?

**Comment by sparment** [comment]
Sorry. I assumed that if there was a solution it should be closed. This was my first issue created on GitHub...

**Comment by RomRider** [comment]
A workaround is not a solution 😉

**Comment by maykar** [comment]
This has been addressed in the latest releases. Current release is 1.4.5. Close if this has been resolved, share any additional info if it has not.

**Comment by sparment** [comment]
The latest release 1.4.5 solved the issue. Thank you!
