### ISSUE TITLE
Headers disappeared

### ISSUE THREAD

**Issue by Korte68** [maykar/custom-header#204]
After updating to HA 0.110.4 the header is disappeared.
Why could be the problem?

**Comment by b4dpxl** [comment]
I had the same thing with all my HACS-added frontend addons after updating HA and HACS. Had to change the URLs in the `.storage/lovelace_resources` from `/community_plugins/...` to `/hacsfiles/...`. 

YMMV.

**Comment by Korte68** [comment]
Thank you.
In my config it was /hacsfiles/...
But i did not have this directory.
I changed back to community_plugins, and after it was working
Thank you

**Comment by maykar** [comment]
Recent versions of HACS have changed. The endpoint is /hacsfiles/ not /community_plugin/ now. HACS should have displayed information about this in your log and this is not related to Custom Header.

**Comment by SAGV** [comment]
For someone who also faces a missing header — try clearing your cache in the browser. Worked for me.

**Comment by maykar** [comment]
For a bit more clarity on HACS: the entry in your lovelace resources should be /hacsfiles/, but the place it stores the actual files is /www/community/

So when installed custom header's file exists in /www/community/custom-header/
But your resources URL should be /hacsfiles/custom-header/custom-header.js

HACS should install to that folder automatically as well as add the correct URL to your resources. You should not change them. 

For more info, check out the HACS readme.

**Comment by Korte68** [comment]
Thaks for the clarification.
in this case the hacsfile is only a logical name of the folder....but i do
not understand why it is caused problem with the compact header...

Ryan Meek <notifications@github.com> ezt írta (időpont: 2020. jún. 1., H,
20:41):

**Comment by maykar** [comment]
So HACS "serves" the files in the community folder to the URL of hacsfiles. This is to prevent caching issues, which is what you ran into. Essentially by not using the correct folder and resource URL you were [installing the card manually](https://maykar.github.io/custom-header/#installation/manual) and when you do that you need to add code to the end of the URL in order to prevent caching issues. So, even though you updated Custom Header, your system was using the old version it had cached and the older version was likely one that wasn't compatible with 0.110.4.

**Comment by Korte68** [comment]
clear. thanks

Now it is working well.

Ryan Meek <notifications@github.com> ezt írta (időpont: 2020. jún. 1., H,
21:52):

**Comment by Korte68** [comment]
until now...
I just changed the raw config, after it the menu bar disappeared again....

What is the problem?

Please help

Kertvéllesy László <kertvlaci@gmail.com> ezt írta (időpont: 2020. jún. 1.,
H, 22:45):

**Comment by Korte68** [comment]
If i uninstall the custom header, the menu bar appear again.
But after reinstall, it disappeared again...

Please help

**Comment by maykar** [comment]
Please read the bots comment (2nd comment on the issue ) and provide the required info

**Comment by Korte68** [comment]
[lovelace.txt](https://github.com/maykar/custom-header/files/4716841/lovelace.txt)

Can not open the raw config editor, because of the issue...I attached the lovelace file which is relevant.

Latest HA 0.110.4
Latest CH 1.47

every browser (Chrome, safari ...)

HACS install

Can you reopen the ticket?

Thank you

**Comment by maykar** [comment]
See the first [2 important notes here](https://maykar.github.io/custom-header/#intro/notes) to restore the default HA header. 

Do you get any errors in the places mentioned in the bot's post?

Also, `"voice": "hide"` is not a valid config option

**Comment by maykar** [comment]
In one exception you use `voice: hide`, change that to `voice_hide: false`. In your main config you use `voice: false` change that to `voice_hide: false` as well.

**Comment by Korte68** [comment]
it was a valid option earlier?

I changed them now. Thank you

Ryan Meek <notifications@github.com> ezt írta (időpont: 2020. jún. 2., K,
13:47):

**Comment by maykar** [comment]
Actually you use many options in your config that are invalid like: `panel: false`, `options: hide`, `header: false`, `menu: false`, all the clock options you have in there and others. It looks like you've just copied your configuration from CCH to CH. 

CH is a new project with many new config options. Almost all config from CCH is no longer used. I suggest reading through the docs to remove options that don't exist.

**Comment by Korte68** [comment]
ok, but I think the migration from CCH to CH was an automatic process.

**Comment by maykar** [comment]
I didn't make anything automatic with the migration. You had to uninstall CCH, install CCH and there were warnings that almost all config options had changed.

**Comment by Korte68** [comment]
So far there was not any problem with the old config.
I removed a lot of them now.
But still not working. Still I made any mistake? 
[lovelace_new.txt](https://github.com/maykar/custom-header/files/4717196/lovelace_new.txt)
Thank you

**Comment by maykar** [comment]
Are you refreshing the page after going into raw config as mentioned in the important notes?

There is also a pre-release that removed this requirement 1.4.9. You can test it out by selecting reinstall in HACS and turning on "show beta"

**Comment by Korte68** [comment]
Yes, refreshing
And oftten reinstall the CH after modifying the file...just to be sure...

**Comment by maykar** [comment]
* Have you tried the latest pre-release?
* Do you get any errors in either of the places that the bot's comment above mentions?

**Comment by Korte68** [comment]
Yes, but not helped.

I started to reconfigure the CH part. Remove all settings, and started
again..

It helped.

Thank you for your help to point me in the right direction

Ryan Meek <notifications@github.com> ezt írta (időpont: 2020. jún. 2., K,
15:46):

**Comment by Korte68** [comment]
After adding this configuration, the menu disappeared again:

                "tabs_color": {
                    "Futes": "{% if (states.switch.kazan_indito_ln1_4.state == \"on\") %}orange{% else %}white{% endif %}  ",
                    "Home": "{% if ((binary_sensor.test_motion2_4 == \"on\")) %} red  {% else %} {% if ((binary_sensor.test_motion5_1 == \"on\")) %} orange {% else %} {% if ((binary_sensor.test_motion4_2 == \"on\")) %} yellow {% else %} {% if ((binary_sensor.test_motion4_6 == \"on\")) %} blue {% else %}white {% endif%} {% endif%} {% endif%} {% endif%}",
                    "Konfig": "{% if (states.binary_sensor.updater.state == \"on\") or (states.sensor.hacs.state | int > 0) %}red{% else %}white{% endif %}",
                    "Medence": "{% if (states.switch.medence.state == \"on\") %}blue{% else %}white{% endif %}",
                    "Napelem": "{% if ((states.sensor.solaredge_current_power.state | int > 8000)) %} red  {% else %} {% if ((states.sensor.solaredge_current_power.state | int > 6000)) %} orange {% else %} {% if ((states.sensor.solaredge_current_power.state | int > 4000)) %} yellow {% else %} {% if ((states.sensor.solaredge_current_power.state | int > 2000)) %} blue {% else %}white {% endif%} {% endif%} {% endif%} {% endif%}",
                    "Ontozes": "{% if (states.switch.ontozo_foszelep_13_1.state == \"on\") %}blue{% else %}white{% endif %}  "
                },


Any idea?

Thank you

**Comment by Korte68** [comment]
I found the problem.
It was a config error.
"tabs_color": {
                   "Home": "{% if ((binary_sensor.test_motion2_4 .....

Should: 

                   "Home": "{% if ((states.binary_sensor.test_motion2_4.state .....

Is it possible to do the CH dumb proof? 

This mistype should not prevent to see the menu bar...

Thank you

**Comment by maykar** [comment]
If you make formatting mistakes in any card, component, even HA config it will cause the thing in question to break or in the worst case scenario prevent HA from starting at all. I do some checking for common mistakes and attempt to prevent the user from using config that will break CH, but I cannot check for everything, especially not formatting mistakes. This would be a large undertaking and decrease the performance of CH.

**Comment by maykar** [comment]
The UI editor of Custom Header is the safest ("dumb proof") option as you're not editing the code yourself, but if you choose to use advanced features and edit the yaml yourself then it's up to you to make sure things are done correctly and the documentation is followed.
