### ISSUE TITLE
Blocking users from "?disable_ch"

### ISSUE THREAD

**Issue by KRA77** [maykar/custom-header#214]
Is it possible to block users from using "?disable_ch" ?

**Comment by maykar** [comment]
Adding this as a config option is a great idea. I think I will only allow it to be set on non-admin users as a safety feature. Good request!

**Comment by maykar** [comment]
Think I might expand this a bit as well. Make a config option like `restrict_users: true` to block the disable feature and remove access to CH settings.

**Comment by KRA77** [comment]
sounds good !

**Comment by maykar** [comment]
[Added in 1.5.3](https://community.home-assistant.io/t/custom-header/155399/841)
