### ISSUE TITLE
sidebar menu

### ISSUE THREAD

**Issue by davide-rhw** [maykar/custom-header#215]
I've problem with "hide sidebar". I want only hide sidebar , not menu. It's work correctly around two weeks ago. What is the setting for hide only sidebar and put menu button in header?
![Schermata da 2020-06-08 14-51-20](https://user-images.githubusercontent.com/58735072/84032556-d19b6780-a997-11ea-97b7-41301d7f65e3.png)

**Comment by maykar** [comment]
Using `disable_sidebar` [Disables and hides the sidebar and menu button](https://maykar.github.io/custom-header/#configuration/main). Not sure why it was working for you before.

If you want this type of behavior then use the HA setting found in the user settings (very bottom sidebar button) and turn on "Always hide sidebar".

**Comment by davide-rhw** [comment]
Yes it's. I think the last upgrade of HA remove me this setting. Thanks so much friend. Very good work
