### ISSUE TITLE
Warning after each update

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#224]
As the issue counter is 0 I'm not sure if you heard about that.
It's a minor thing for now but maybe an issue with further HA-versions-

HA 110.4
CH 1.5.8 installed via HACS
HA on Rasp3+ Hass.io

Issue:
````
Protokolldetails ( WARNING )
Logger: hacs.repository.plugin.maykar.custom-header
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 8:28:26 (1 occurrences)
Last logged: 8:28:26

'install' is deprecated, use 'async_install' instead
````
The issue appears only after every update.
No further errors. CH is working completely without any issues.

**Comment by maykar** [comment]
This is a [HACS issue](https://community.home-assistant.io/t/custom-header/155399/845?u=mayker)
