### ISSUE TITLE
Auto Cycle views

### ISSUE THREAD

**Issue by codeclinic** [maykar/custom-header#227]
In-order to screen burn /ghosting on my HA kiosk display I'd really appreciate a feature that would make HA cycle through the various views on a time cycle. So for example it's start on the default view/tab then move to display the next view after a defined period of time, then move to display the next view and so on.

If you could implement this, I'd be really grateful.

Thanks.

**Comment by maykar** [comment]
This isn't something I'd add to CH, but you can do this with [hass-browser-mod](https://github.com/thomasloven/hass-browser_mod). It has two features that would help you. You could use the [navigate](https://github.com/thomasloven/hass-browser_mod#navigate) feature to create an automation that would cycle through tabs or you could use the [blackout](https://github.com/thomasloven/hass-browser_mod#blackout) feature to prevent screen burn. 

Keep in mind that even though you're cycling through the tabs, there will still be elements that don't move and could cause burn in.

**Comment by codeclinic** [comment]
Ok, I'll take a look at those. thanks.
