### ISSUE TITLE
Installation on YAML Frontend

### ISSUE THREAD

**Issue by rjenx** [maykar/custom-header#228]
I downloaded via HACS this module, unfortunately it would not load. The documentation says "Go to your Lovelace dashboard resources found under "Configuration" in your sidebar: Configuration > Lovelace Dashboards > Resources. Click the plus icon on the bottom right and add **/local/custom-header.js?v=0.0.1** as your URL and select "Javascript Module" as the resource type. Any time you update you need to change version number at the end of the URL to prevent caching issues"

I inserted the url in my config file as follows:
`resources:
    - url: /hacsfiles/custom-header/custom-header.js?v=0.0.1
      type: module`
On my system this is incorrect, you have to remove the "?v=0.0.1" for it to work. 

Home Assistant 0.111.4

**Comment by maykar** [comment]
What documentation is telling you that? Seems to me you combined the HACS method and Manual method from the installation docs.
