### ISSUE TITLE
Toggle to force arrows/scrolling on or off

### ISSUE THREAD

**Issue by MCManiac52** [maykar/custom-header#229]
See the attached screenshot - I've got 6 tabs visible on my phone, if I remove one, they all show fine, but with the 6th one, I get the scroll arrows, but if the arrows weren't there, all the icons would fit. Could we have a toggle to force the arrows on or off?

**Comment by MCManiac52** [comment]
https://imgur.com/T1HVX2x

**Comment by maykar** [comment]
Those arrows are called "chevrons" and this is something you can already do. [Read the first config item here.](https://maykar.github.io/custom-header/#configuration/tabs)
