### ISSUE TITLE
Custom Header causes Lovelace menu items to not work in 0.112.0b0

### ISSUE THREAD

**Issue by SeanPM5** [maykar/custom-header#232]
After updating to 0.112.0b0, the default menu items in Lovelace menu do not work. The only menu option that works is for Custom Header.

![image](https://i.imgur.com/uzbm0OW.png)

This means that nobody can configure their UI, refresh, reload resources, see unused entities, etc. Can't even click the "Help" link either. Nothing is printed in console it seems, it just doesn't work. Reproduced on Chrome desktop (Mac) and iOS App. 

Confirmed that it was Custom Header causing it because when adding `?disable_ch` to the end of the URL, the menu worked as expected. I am using Custom Header 1.6.3 which is the latest in HACS.

**Comment by maykar** [comment]
Thank you, on it.

**Comment by maykar** [comment]
1.6.4 should remedy the issue.

**Comment by SeanPM5** [comment]
Confirming that 1.6.4 does indeed fix this on my end. Thank you!

**Comment by Krocko** [comment]
I have the same problem with an iOS device.

**Comment by Krocko** [comment]
@maykar could it be the same problem like this:
https://github.com/hacs/frontend/pull/181?

**Comment by maykar** [comment]
Likely a similar issue, but different elements. HA no longer uses `paper-item`, instead it uses `mwc-list-item`. Will work on this soon and will let you know when I have a beta to test out.

**Comment by maykar** [comment]
@Krocko Please give the latest pre-release `1.6.6` a try and let me know how it goes.

 To view pre-releases in HACS go to the Custom Header listing under "Frontend", click the 3 dots in the right hand corner, select "Reinstall", turn on "Show beta versions", select 1.6.6, and hit "Install". Clear cache afterwards just in case.

**Comment by Krocko** [comment]
@maykar It is working. 
Thank you very much!

**Comment by Harry-1976** [comment]
@maykar Perfect! It also solves the multiple tapping that was required to access the menu items. Now i can access them with a single tap.
