### ISSUE TITLE
iOS can't access menu items [ Fixed in pre-release 1.6.6 ]

### ISSUE THREAD

**Issue by aptonline** [maykar/custom-header#235]
Noticed that in Safari and the HA app I’m unable to enter Configure UI mode from the ... menu when I have Custom Header enabled.

Initially I thought this was a HA issues but @ludeeus advised me to disable Custom Header and test which resolved the issue.

Home assistant: 0.112.2
Custom Header: 1.6.5

**Comment by maykar** [comment]
This has already been addressed in the latest pre-release 1.6.6

To view pre-releases in HACS go to the Custom Header listing under "Frontend", click the 3 dots in the right hand corner, select "Reinstall", turn on "Show beta versions", select 1.6.6, and hit "Install". Clear cache afterwards just in case.

**Comment by maykar** [comment]
Pushed full release with no other changes to prevent further issues.
