### ISSUE TITLE
Gone from the menu

### ISSUE THREAD

**Issue by zkab** [maykar/custom-header#236]
I have been using Custom Header for a while and it has worked OK ... after last update of Hassio I can't see Custom Header in the menu.
Installation was done manually.
Have following:

HassOS 4.11
HA 0.112.2
Custom Header: 1.6.7

How do I get Custom Header back again in the menu?

**Comment by lgxmedia** [comment]
can't see the bar anymore, deleted all settings related with custom-header and same. All was fine until last update!

**Comment by maykar** [comment]
I cannot help without information. Both of you, read the bot's comment above and provide as much information as you can. I am on HA 0.112.2 and am not seeing any issues.

**Comment by antoineguilbert** [comment]
Same error for me. Here some errors from the browser console. I've the problem on desktop (Safari, Chrome) and also on Home Assistant (Android). 

Hope it will help !

<img width="1276" alt="Capture d’écran 2020-07-06 à 08 32 36" src="https://user-images.githubusercontent.com/16510381/86562685-637c9d00-bf63-11ea-8f2c-9de4f1b9b157.png">

**Comment by zkab** [comment]
No - I am using GUI mode.
What I see when clicking the 3 dots is:

- Configure UI
   - Unused entities
   - Raw configuration editor
- Help

And here is section from RAW custom_header:

  active_tab_css: 'background: #6e8993; color: #fff;'
  all_tabs_css: 'color: white;'
  chevrons: false
  compact_mode: true
  disable_sidebar: true
  header_css: 'background: #333333; padding: 5px'
  hidden_tab_redirect: false
  hide_help: true
  hide_rawue: true
  hide_unused: true
  options_hide: tr
  shadow: false
  
I am using Chrome both in Linux & Android ... but still no Custom Header

**Comment by maykar** [comment]
If you installed manually are you adding to a version number at the end of your resources URL as explained on the [installation page](https://maykar.github.io/custom-header/#installation/installation)?

Just to reiterate the information the bot asked for since no one has given me the full details of their issue yet and partial information isn't helpful:

* CH config
* Errors in log or browser dev tools (F12)
* HA & CH versions
* Installation method (HACS or Manual)

@zkab Please share any errrors, you've given me everything else.

**Comment by zkab** [comment]
As you can see I added a version number at the end of my resources URL:
/local/custom-lovelace/compact-custom-header/custom-header.js?v=1.6.7

Here is the information you asked for ... 

1) HA 4.11
2) CH 1.6.7
3) CH config (from RAw configuration editor)
`
custom_header:
  active_tab_css: 'background: #6e8993; color: #fff;'
  all_tabs_css: 'color: white;'
  chevrons: false
  compact_mode: true
  disable_sidebar: true
  header_css: 'background: #333333; padding: 5px'
  hidden_tab_redirect: false
  hide_help: true
  hide_raw: true
  hide_unused: true
  options_hide: true
  shadow: false
 `
4) Installation method = Manual
5) System log (no errors)
`20-07-05 18:34:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-05 18:34:47 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-05 19:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-05 19:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-05 19:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-05 20:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-05 20:41:27 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-05 20:41:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-05 20:41:27 INFO (MainThread) [supervisor.host.services] Update service information
20-07-05 20:41:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-05 20:41:27 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-05 20:41:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-05 20:41:27 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-05 22:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-05 22:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-05 22:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-05 22:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-05 22:48:07 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-05 22:48:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-05 22:48:07 INFO (MainThread) [supervisor.host.services] Update service information
20-07-05 22:48:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-05 22:48:07 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-05 22:48:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-05 22:48:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 00:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 00:54:47 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 00:54:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 00:54:47 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 00:54:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 00:54:47 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 00:54:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 00:54:47 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 01:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-06 01:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-06 01:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-06 02:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 03:01:27 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 03:01:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 03:01:27 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 03:01:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 03:01:27 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 03:01:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 03:01:27 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 04:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-06 04:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-06 04:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 04:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-06 05:08:07 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 05:08:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 05:08:07 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 05:08:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 05:08:07 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 05:08:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 05:08:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 06:08:07 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
20-07-06 06:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 07:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-06 07:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-06 07:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-06 07:14:47 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 07:14:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 07:14:47 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 07:14:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 07:14:47 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 07:14:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 07:14:47 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 08:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 09:21:27 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 09:21:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 09:21:27 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 09:21:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 09:21:27 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 09:21:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 09:21:27 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 10:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-06 10:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-06 10:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 10:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-06 10:48:02 INFO (SyncWorker_19) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-64-homeassistant
20-07-06 10:48:20 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-07-06 10:48:30 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-07-06 11:28:07 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 11:28:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 11:28:07 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 11:28:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 11:28:07 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 11:28:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 11:28:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 12:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-06 13:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-06 13:08:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-06 13:08:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-06 13:34:47 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-06 13:34:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-06 13:34:47 INFO (MainThread) [supervisor.host.services] Update service information
20-07-06 13:34:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-06 13:34:47 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-06 13:34:47 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-06 13:34:47 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-06 14:08:07 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json`

6) Browser Dev Tools from Chrome ver 83.0.4103.116

`battery-state-card.js:1  BATTERY-STATE-CARD  1.3.2
custom-header.js?v=1.6.7:617   CUSTOM-HEADER    Version 1.6.7  
custom-header.js?v=1.6.7:617 Current User's Name:  Rajan
custom-header.js?v=1.6.7:617 Current User's ID:  5222d90c72aa420095a87257286dddd9
custom-header.js?v=1.6.7:617 Device ID:  b177e09f-fd27dbb5
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://192.168.1.4:8123/local/custom-lovelace/battery-state-card/battery-state-card.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by maykar** [comment]
@zkab Okay, so that confirms it. Everyone else posting here is having a different and unrelated issue than you. I asked in an earlier comment, but didn't get an answer: Is everything else working with CH (compact mode, disabled sidebar, etc)?

As far as missing the Custom Header option in the options menu, you're hiding the options menu with `options_hide: true`

**Comment by zkab** [comment]
Sorry that I gave you information that were confusing ... I forgot that I had 'options_hide: true' in my configuration.
My fault and I appreciate you taking time to sort it out ... thanks for your patience.
Now I am airborne again ... CH is a great product ...

**Comment by maykar** [comment]
@antoineguilbert & @lgxmedia 

If you're still having problems, please create a new issue with the requested information.
