### ISSUE TITLE
Adding custom-header.js resource makes the top bar disappear on 0.112.3

### ISSUE THREAD

**Issue by cpiekacz** [maykar/custom-header#237]
I've just updated the HA to 0.112.3 and noticed that the top bar disappears completely, even if I remove all the configuration from ui-lovelace.yaml, it's enough that I add custom-header.js to resources section in configuration.yaml:

```
    - url: /local/custom-header.js?v=1.6.7
      type: module
```

**Comment by cpiekacz** [comment]
And forgotten error log:

```
Logger: frontend.js.latest.202007021
Source: components/system_log/__init__.py:209
First occurred: 10:04:23 (4 occurrences)
Last logged: 10:06:47

https://***:8123/local/custom-header.js?v=1.6.7:1:16389 Uncaught TypeError: Cannot read property 'cloneNode' of null
```

**Comment by maykar** [comment]
Can you confirm that you see the correct version reported in your browser's dev tools console:

![image](https://user-images.githubusercontent.com/25127328/86916923-4c1fea00-c0f2-11ea-8656-223a1af41509.png)

**Comment by cpiekacz** [comment]
Ok, that was it, even though I've changed the parameter to reload the component, I still had the old version cached. 1.6.7 works correctly. Thanks.
