### ISSUE TITLE
Allow tab on a secondary Lovelace Dashboard to be set the default tab

### ISSUE THREAD

**Issue by ha14937** [maykar/custom-header#238]
With the addition of multiple dashboards, it would be great to be able to, based on exceptions/conditions, make a tab on a secondary dashboard the default tab. This is not a huge deal - as there are workarounds such as making different tabs on the Overview dashboard - but it sure would be easier to be able to specify a completely different dashboard.

**Comment by maykar** [comment]
Sorry to say, but I have yet been able to do this in a way that doesn't cause issues. The way the dashboards operate makes adding this option too problematic and buggy. I will keep at it, but I don't think there is a good way for CH to handle this at the moment.

For now, this might be of interest:

https://community.home-assistant.io/t/any-way-to-force-some-users-to-a-dashboard-other-than-overview/205901
