### ISSUE TITLE
date and time

### ISSUE THREAD

**Issue by terminet85** [maykar/custom-header#24]
Hey,
great job! Can you please add date and time feature as CCH?
Thanks

**Comment by maykar** [comment]
This already exists, read through [button config](https://maykar.github.io/custom-header/#configuration/buttons) and the [templates section](https://maykar.github.io/custom-header/#templates/templates) of the docs, both pages even provides examples for what you're trying to do.

**Comment by terminet85** [comment]
Thank you for your quickly reply, maybe as advice, could be most noted, because this is a change of behavior as before.

**Comment by jsiemonski** [comment]
@terminet85 were you able to get time and date to work? I've tried using header_text in compact mode, and it won't show up for me. It does if I add it as a button, but it looks weird and I don't like it.

**Comment by maykar** [comment]
Header text doesn't exist in compact mode as removing it is what makes the header compact. What looks weird about the button time and date? Maybe I can help.

**Comment by jsiemonski** [comment]
Ah, that makes sense :) Can we make the button not clickable?

**Comment by 3ative** [comment]
The trouble with having the Time & Date has 'Header' text is, as has been noted, this needs two lines.
With the old CCH we could replace right-hand buttons with Time & Date. Can we have that with this version too?

**Comment by maykar** [comment]
Last example on this page: https://maykar.github.io/custom-header/#configuration/buttons

**Comment by maykar** [comment]
iantrich just shared this on discord:

![image](https://user-images.githubusercontent.com/25127328/70941108-c0415600-2019-11ea-980c-b6f5f7a54d3b.png)


```
  button_text:
    options: >-
      {{ hours12 }}:{{ minutesLZ }} {{ ampm }} - <ha-icon icon='mdi:weather-{{
      states.weather.dark_sky.state }}'></ha-icon> {{
      states.weather.dark_sky.attributes.temperature }}°
```

**Comment by jsiemonski** [comment]
That works, thank you!
