### ISSUE TITLE
Cannot operate exceptions per user

### ISSUE THREAD

**Issue by vinzzs** [maykar/custom-header#240]
Hello I can't manage to make the exeptions work to have different views depending on the user, although I browse the forum none of the examples works! And I see this error message in the log: 'hacsfiles/frontend-202007180957.js:1:17185 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "hacs-single-page-layout" has already been used with this registry'

Thank you

**Comment by maykar** [comment]
I can't really help without seeing what your config is. Please read the bots comment above and provide as much info as possible. Also, thats a HACS error and it has nothing to do with Custom Header.
