### ISSUE TITLE
Menu options no longer work on mobile in HA 0.114

### ISSUE THREAD

**Issue by Krocko** [maykar/custom-header#243]
After home assistant update to 0.114 beta, the top right menu in lovelace don't work anymore. 

![image](https://user-images.githubusercontent.com/29394115/89523926-f79c8700-d7e3-11ea-8921-2e405e23a6ff.jpeg)

**Comment by maykar** [comment]
Please try the latest release (1.6.8) and report back.

**Comment by Krocko** [comment]
Thank you for your fast work. 
But it is still not working.

**Comment by maykar** [comment]
Looks like it ends up nested inside the help option in 0.114 for some reason. As a work around till I get a fix in make sure you're not hiding the help item

**Comment by maykar** [comment]
Actually, the fix in 1.6.8 seems to have fixed that as well. Please be sure that the latest version is loaded 1.6.8 by opening your browsers dev tools console. You should see the latest version:

![image](https://user-images.githubusercontent.com/25127328/89537788-cdd56700-d7c7-11ea-970d-d4fff3d08aa0.png)

If you do not, either refresh while clearing cache CTRL+SHIFT+R or reinstall and do the same.

**Comment by maykar** [comment]
Also, I just noticed that you have both "Refresh" and "Unused Entities" in that menu. That usually indicates you are using yaml mode. The UI editor is not available in yaml mode.

**Comment by Krocko** [comment]
But the refresh should work. 
I tested it on pc. There it is work. But on mobile (iOS) not.

**Comment by maykar** [comment]
Oh okay, I've misunderstood. Will look into it when I can get on one of my ancient iOS devices.

**Comment by tomlut** [comment]
Yeah just came to report this issue with the 0.114b2 release on the iOS app. Desktop browsers (firefox & Chrome) are fine.

**Comment by maykar** [comment]
Please give 1.6.9 a try and report back

**Comment by Krocko** [comment]
It is working now. 
Thank you very much!
