### ISSUE TITLE
Make it so the Config Items are in the same order in Main and under Conditions

### ISSUE THREAD

**Issue by jschwalbe** [maykar/custom-header#251]
Currently we have this under Main:
![image](https://user-images.githubusercontent.com/8005921/90963648-874e6080-e487-11ea-944b-9c0dd7edb288.png)
and this under Conditions:
![image](https://user-images.githubusercontent.com/8005921/90963662-a0571180-e487-11ea-88aa-04a2fe2ba6b3.png)

I propose inserting one blank space under the Conditions sections where `Restrict Users` would be, so that the items line up. It would be more cosmetic and make workflow a bit nicer when comparing one to the other.

Looks like it has something to do with this code found in editor.js:
```
        ${!this.exception
          ? this.haSwitch(
              'restrict_users',
              true,
              false,
              localize('editor.restrict_users_title'),
              localize('editor.restrict_users_tip'),
            )
          : ''}
```
Looks like it might be an easy fix, but that's the extent of my knowledge of coding, however.

**Comment by maykar** [comment]
Added to latest release 1.7.1
