### ISSUE TITLE
[MOBILE] Permission user see only one card

### ISSUE THREAD

**Issue by Wirux** [maykar/custom-header#252]
Hi
I have a problem, I want to give access to only one card by the user, hide all bars and set as default for example '2'.
All works fine on PC browser but when I had logged, on my phone browser (app have the same problem) I can go back into the default page [which I do not want to share with this user] after tapping entity and pressing two times "back" button on the phone
Have someone the same problem?

HA version: 0.114.3
Install by -> HACS version:1.5.2
CH version:1.7.0

**Comment by maykar** [comment]
Custom Header cannot redirect until lovelace has loaded, this has the side effect of whatever page was loaded first remains in your browsers history. I cannot prevent this, but if you set their default tab as the first lovelace tab it would solve this issue.

**Comment by maykar** [comment]
Thought about it a bit and snuck a modification to redirects into the latest release (1.7.1). Would be interested to see if it helps your issue.
