### ISSUE TITLE
iOS Split Mode Bottom Icons don't always navigate

### ISSUE THREAD

**Issue by GirzzlyAK** [maykar/custom-header#253]
**ISSUE**
On the iOS HA Companion App, using Custom Header with default settings _except_ for Split Mode and Compact Mode enabled, often when selecting a new icon (tab) at the bottom, the icon highlights, and the underline moves to that icon, but the respective page does not appear (it remains on the previous one). Tapping it again often works, but this behavior appears to be random, and does not exhibit this behavior on Firefox on my Windows 7 machine.

I've had other issues with the browser used by the companion app differing in functionality from my desktop, so this may be a problem with the iOS app itself.

**CONFIG**
```
custom_header:
  chevrons: false
  compact_mode: true
  header_text: Home Assistant
  hidden_tab_redirect: false
  shadow: false
  split_mode: true
```
**VERSIONS**
HA 0.114.0
CH 1.6.9
iOS Comp App 2020.4.1 (1)

**THEMES**
Home Assistant backend-selected Dark mode

**INSTALLATION METHOD**
Manual

In this screenshot, the icon 'selected' is on the far right, but the page displayed (the previous page) is the one two icons to the left.

![IMG_0256](https://user-images.githubusercontent.com/4411963/91109596-ef3bad00-e627-11ea-8e04-9dbee792d062.PNG)

**Comment by maykar** [comment]
Does this only happen in split mode?

**Comment by GirzzlyAK** [comment]
Ryan, 

Actually, I was just testing this last night, and it appears to be the case. I like the icons at the bottom as they are easier to access. I’ll try using them a couple of days at the top to see if it happens. 

I have not experienced this on the desktop. Mine is an iPhone 7 with iOS V13.5.1 but I just got notification of v13.6.1, so I will upgrade. I don’t expect it to cure this tho. I do believe it may be related to the browser support in the app itself or the interaction with the method you use is o do what you do. I have noticed that it does not always honor CSS correctly.  

Maybe we can get your work integrated into the official app release! It is more usable IMO. 

Cheers,
Shane

**Comment by GirzzlyAK** [comment]
Ryan,

Be aware that I was able to reproduce this behavior in Footer mode with split mode switched off. It likely uses a lot of the same code tho, so not surprised. Jus my another data point. I’ve switched to default settings for now. 

Shane

**Comment by maykar** [comment]
`Maybe we can get your work integrated into the official app release! It is more usable IMO.`

Thank you for the kind words, but Custom Header is just Javascript applied to the Lovelace interface. While it's features may be adopted into core HA and it's companion apps (some already have), they would need to be added in a much more integrated way.

Looking into your issue a bit more currently.

**Comment by GirzzlyAK** [comment]
Ok, that didn’t take long. I was just able to reproduce the behavior twice relatively quickly with default settings, icons at the top. It appears that the tap is registered, it highlights, but sometimes the icon underbar doesn’t respond (move to the taped icon), and sometimes it does move, and in neither case did the web page update to that new page, but remained on the old one. So the final state, was icon for one page underlined, but the previous page was still displayed. 

Hope that helps. Let me know if there is anything in particular I can test for you. 

Shane

**Comment by maykar** [comment]
Noticed in your original post that you were using HA 0.114.0 & CH 1.6.9, have you tried updating both to the current versions. HA 0.114.3 and CH 1.7.2?

**Comment by GirzzlyAK** [comment]
No it yet, but will do so today.

**Comment by GirzzlyAK** [comment]
FYI, I updated and the issue still exists. 

Shane

**Comment by maykar** [comment]
Just wanted to make sure I got all the info,

**Comment by maykar** [comment]
What's the device and iOS version?

**Comment by GirzzlyAK** [comment]
I think I put that in the original post or follow up, but I’m on an iPhone 7 and iOS 13.5.1. I did just get a notification for 13.7 but haven’t had a chance to update yet.

**Comment by maykar** [comment]
Nah, you did mention it and I just missed the post, which is why I deleted my question after finding it. Still trying to replicate this, but the iOS devices I own are very old at this point and behave differently, but I'm on it.

**Comment by GirzzlyAK** [comment]
No worries. Not a big deal. A second tap gets me there.

**Comment by fti7** [comment]
I have the same issue. With the Bar at the Button, but on an Android Tablet.
Custom Header 1.7.7
Any Updates on this?

**Comment by Gio76** [comment]
I have been experiencing the same issue for several weeks now. When tapping on a different view, most of the times nothing happens. To actually make the change I need to double-tap. See below my setup info:

**CONFIG**
```
custom_header:
  chevrons: false
  compact_mode: true
  shadow: false
```
**VERSIONS**
- Home Assistant 0.115.0b8
- supervisor 243
- iOS Companion App 2020.6 (14)
- Custom Header 1.7.7


**INSTALLATION METHOD**
- HACS

**SCREEN RECORDING**
![screen_recording](https://user-images.githubusercontent.com/26906928/93024827-65c63c00-f623-11ea-9b77-35466c22779b.gif)

**Comment by GirzzlyAK** [comment]
Cool setup! Love the buttons! You wouldn’t want to share the code for one of those I could use for a template, would you? ;-)

 

Shane

 

All truths are easy to understand once they are discovered. The point is to discover them.

-- Galileo

**Comment by Gio76** [comment]
Sure thing @GirzzlyAK. Drop me a PM and I'll share the code as soon as I have a spare moment 😄

**Comment by Gio76** [comment]
@maykar any updates on this bug? Thanks in advance!

**Comment by maykar** [comment]
Please do not bump & tag me on issues. If there is an update pertaining to a particular issue, I will post in the issue to notify all those involved and subscribed to it. Be assured, if there is an open issue I am working on it when I am able to do so. I have been testing different solutions to this issue since it was first posted and am currently working on a beta release so that you all may test it out, when it is up and ready I will inform you.

Please, try to be patient with issues, feature requests, etc. [This post on open source etiquette](https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38) is a good read. Especially numbers 6-9.

**Comment by maykar** [comment]
This has been addressed in the latest pre-release 1.7.8. Please, report back here and let me know if it has fixed your issues.

To view pre-releases in HACS go to the Custom Header listing under "Frontend", click the 3 dots in the right hand corner, select "Reinstall", turn on "Show beta versions", select 1.7.8, and hit "Install". Clear cache afterwards just in case.

If you do not see the version 1.7.8 reported in your browser's dev tools console (F12). You may need to reinstall or clear cache. If you installed manually, make sure you're adding to the URL version number in your Lovelace resources.

**Comment by Gio76** [comment]
> Please do not bump & tag me on issues. If there is an update pertaining to a particular issue, I will post in the issue to notify all those involved and subscribed to it. Be assured, if there is an open issue I am working on it when I am able to do so. I have been testing different solutions to this issue since it was first posted and am currently working on a beta release so that you all may test it out, when it is up and ready I will inform you.
> 
> Please, try to be patient with issues, feature requests, etc. [This post on open source etiquette](https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38) is a good read. Especially numbers 6-9. Though his tone is a bit harsher than I would personally use. If an issue doesn't affect me personally, it still interests me and I am motivated to fix it. I enjoy puzzles and every issue is a new puzzle or challenge.

Roger that! it wasn't my intention to be pushy and certainly didn't want to come acroos as rude, my bad.

**Comment by maykar** [comment]
No worries at all. A combination of a bad day and multiple requests for ETA's on features/bugs on multiple projects resulted in venting. Glad to hear it works for you, going to close this one for now.

If anyone else is still having issues with this, please let me know here and I will reopen.
