### ISSUE TITLE
Compact mode hides the whole header

### ISSUE THREAD

**Issue by VictorLamoine** [maykar/custom-header#257]
Lovelace configuration:
```
custom_header:
  compact_mode: true
```

- Installation: HACS
- Lovelave mode: Storage

pip packages:
```
hacs-frontend           202008231558
hass-nabucasa           0.35.0      
home-assistant-frontend 20200824.0  
homeassistant           0.114.3   
```
- `custom-header` version: 1.7.2
- Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0 

![Screenshot_20200826_193916](https://user-images.githubusercontent.com/5566160/91337697-10410100-e7d4-11ea-94c5-e88b6219f717.png)

**Comment by maykar** [comment]
Do you only have one Lovelace view?

**Comment by maykar** [comment]
Any errors from the two places mentioned in the bots comment above?

**Comment by VictorLamoine** [comment]
Sorry I should have included a screenshot with the header, here it is:
![Screenshot_20200826_221938](https://user-images.githubusercontent.com/5566160/91352789-a3853100-e7ea-11ea-8dc1-1e7cc2644b0d.png)

Yes version 1.7.2:
![Screenshot_20200826_222325](https://user-images.githubusercontent.com/5566160/91353267-4f2e8100-e7eb-11ea-8e7c-21f5d1b34a93.png)

- I have multiple Lovelace views
- No error in the logs (I have it set to `error` by default)
- Both Chromium and Firefox are affected

Please let me know how I can help you reproduce/trace the problem :pig:

**Comment by maykar** [comment]
Strange. The only config you use is what you shared above, just `compact_mode: true`?

**Comment by VictorLamoine** [comment]
Yes exactly, nothing more, nothing less

**Comment by maykar** [comment]
Just got home and did some testing on my Linux machine and can't replicate this. With no errors either I don't have much to go on. What other custom frontend addons do you have installed?

**Comment by VictorLamoine** [comment]
I have removed some HACS integrations (google dark theme, simple thermostat) and now it works.
'Problem' is that if I add these integrations again it still works.

I restart home assistant and wait for a minute for everything to be completely started when I install/uninstall anything in HACS.

Sorry for the trouble, if it happens again I'll track more carefully the integrations
