### ISSUE TITLE
Cannot read property 'shadowRoot' of null

### ISSUE THREAD

**Issue by jo-me** [maykar/custom-header#267]
Ha 0.115.3
Custom header 1.8.0

Noticed a CH error in the log after opening HA using the official android app.
There were some similar  issues in previous versions.

Logger: frontend.js.latest.202009182
Source: components/system_log/__init__.py:193
First occurred: 20:53:06 (1 occurrences)
Last logged: 20:53:06

https://192.168.178.45:8123/hacsfiles/custom-header/custom-header.js:146:49227 Uncaught TypeError: Cannot read property 'shadowRoot' of null

**Comment by maykar** [comment]
This applies to both issues you just submitted. Ensure that the latest version is installed using the the info from at the beginning of the bots reply above on a computer or another browser that can show you the dev tools console. If that reports version 1.8.0, make sure that the companion app is using the latest by clearing it's cache. Hold down on the app icon and select "App Info", then click "Storage and cache", then click "clear cache".

If both of your issues are still a problem, please follow the bots comment above and provide the as much of the necessary information as you can so I can try to replicate the issue.

My phone is an Android phone and I use the companion app, I have neither of these issues. In order for me to replicate the issues, I need info and to make sure it's not a cache/install issue.

**Comment by maykar** [comment]
This also seems like an issue that may have been fixed by 1.8.3, please let me know if updating helps. If not I will reopen this issue and investigate further.

**Comment by jo-me** [comment]
Will do. Thanks!

Ryan Meek <notifications@github.com> schrieb am Mi., 30. Sep. 2020, 22:13:
