### ISSUE TITLE
Hide 'CH Settings' does not respect GET parameter ?disable_ch

### ISSUE THREAD

**Issue by SimplyLinn** [maykar/custom-header#270]
When you enable the option hide_ch_settings, the CH Settings option disappears, even when the GET-parameter ?disable_ch is put into the URL.

If this is by design, I suggest adding an explicit note about this option in:
https://maykar.github.io/custom-header/#intro/notes

If this is a mistake...
Here's the bug report!

**A copy/paste of your Custom Header config (found in "Raw Config Editor" or ui-lovelace.yaml)**
```yaml
custom_header:
  hide_ch_settings: true
```
**Any errors relevant to Custom Header found in the HA logs**
None  
**Any relevant errors found in your browsers dev console (F12)**
None  
**The version of Home Assistant and Custom Header you are using**
HA: 0.115
CH: 1.8.3
**The browsers or apps that are affected (i.e. Firefox, Chrome, Chrome Mobile, iOS HA Companion app, etc.)**
Currently only tested on Windows Chrome Version 85.0.4183.121 (Official Build) (64-bit) and Android App
**Installation method (HACS or manual)**
HACS
**HA config method (YAML or Storage). If you don't know what this means, you're using Storage mode**
I don't know, so I'm in storage mode.

**Comment by SimplyLinn** [comment]
Sidenote, for anyone finding this issue and just wanna solve their issue of not being able to edit their custom header, here's the workaround I used:

1. Go to the dashboard you wanna fix with ?disable_ch set into the URL
2. Click "Edit Dashboard" at the 3 dots top right
3. Click "Raw configuration editor at the 3 dots top right (menu have changed post entering "edit mode")
4. Scroll to the bottom and remove any lines with `hide_ch_settings: true` under the custom_header section
5. Save
6. Reload

**Comment by maykar** [comment]
Not intentional, side effect of another fix. Working on a solution now.

**Comment by maykar** [comment]
I have decided to stop work on Custom Header and will be archiving the project. Please, see the following post for more info:

https://community.home-assistant.io/t/custom-header/155399/1100
