### ISSUE TITLE
since HA update to 0.116.0 background is grey

### ISSUE THREAD

**Issue by Uniwatcher** [maykar/custom-header#273]
### I always had a transparant header background. Since the update it's grey

Custom header config:
`
custom_header:
  background: 'rgba(0, 0, 0,.50)'
  compact_mode: true
  shadow: false
`

HA version: 0.116.0
Custom Header version: 1.8.3
Installation method: Hacs
Lovelace Mode : Storage

![before](https://user-images.githubusercontent.com/42183634/95376343-400a1b00-08e1-11eb-86c6-6c2f835f7e7e.JPG)
![after](https://user-images.githubusercontent.com/42183634/95376364-48625600-08e1-11eb-8130-75585fd7a1e2.JPG)

**Comment by maykar** [comment]
I have decided to stop work on Custom Header and will be archiving the project. Please, see the following post for more info:

https://community.home-assistant.io/t/custom-header/155399/1100
