### ISSUE TITLE
Time to right

### ISSUE THREAD

**Issue by tbkon3** [maykar/custom-header#31]
In previous version of costom header i use this configuration:
cch:
  menu: hide
  options: clock
To switch time at position of options button and time was on right side as i want.

Now i'm using this config:
custom_header:
  header_text: '{{ time }}'
  compact_mode: true
  hide_help: true
  voice_hide: true

But time is invisible.

If i use:
custom_header:
  header_text: '{{ time }}'
  hide_help: true
  voice_hide: true
With this config the time is on the left side.

The documentation don't explain how to set time to right side.
Can you help me to config time correctly?

Thank you.

**Comment by maykar** [comment]
Header text is removed to make compact_mode work. You want to change your button's text (bottom of page):

https://maykar.github.io/custom-header/#configuration/buttons

```
custom_header:
  button_text:
    options: '{{ time }}'
```
