### ISSUE TITLE
Cards drawn above page Kiosk mode when panel: true

### ISSUE THREAD

**Issue by wbilger** [maykar/custom-header#33]
If using kiosk: true and panel: true for tab, then the cards begin to draw above the page.
If hide_header: true is added, then kiosk mode works, sort of. The header is drawn at the bottom, although blank, so the page is longer than it shouild be (can notice on mobile via scrolling)
hide_header: true works on it's own as well in the same manner.

**Comment by noxhirsch** [comment]
Same issue here with HA 0.103.0, CH 1.0.3 on Chrome 79.0.3945.79 (Win10). No errors in console & log.
![header](https://user-images.githubusercontent.com/30938717/70971937-781a4600-20a2-11ea-986a-2824ccab0312.PNG)

**Comment by maykar** [comment]
Please, give the latest release v1.0.4 a try

**Comment by noxhirsch** [comment]
For me it's working! :)

**Comment by wbilger** [comment]
Works for me as well. Thanks so much!
Note, if you use kiosk_mode: true, as well as hide_header: true, it pushes blank space to bottom of page.
There is no reason to do so, but thought I would point it out.
