### ISSUE TITLE
Menu in drop-down does not trigger menu open

### ISSUE THREAD

**Issue by olekenneth** [maykar/custom-header#48]
Testing on my iPhone XS in the app and safari. 

After moving the menu button to options/drop-down, clicking the button doesn't work. Nothing happens.

**Comment by maykar** [comment]
Does the "custom header" option bring up settings when clicked (if you're not using YAML mode)?

**Comment by maykar** [comment]
Also, try the latest version v1.0.9 as it tries to address this issue

**Comment by olekenneth** [comment]
Fixed with 1.0.9
