### ISSUE TITLE
Add "Refresh" to options menu

### ISSUE THREAD

**Issue by dooz127** [maykar/custom-header#49]
The documentation mentions the ability to hide the "Refresh" option (from the lovelace-gen module?):

https://maykar.github.io/custom-header/#configuration/main

It'd be nice if there was an option to show "Refresh" if it isn't already in the options menu from another module.

**Comment by iantrich** [comment]
@dooz127 refresh is an option if you are using yaml mode for Lovelace, only.

**Comment by maykar** [comment]
Like ian pointed out, that is a YAML mode only feature. When using YAML mode there is a need to refresh the configuration after updating `ui-lovelace.yaml`, otherwise there is no need for that option.
