### ISSUE TITLE
Docs site offline

### ISSUE THREAD

**Issue by johntdyer** [maykar/custom-header#55]
the gh pages site doesnt work

https://maykar.github.io/custom-header/

I get this error 

TypeError: Error resolving module specifier: @polymer/polymer/lib/utils/wrap.js

appears some dep is wrong

**Comment by maykar** [comment]
Yeah, something going on with github pages at the moment. Updated docs and build is now failing out of the blue (well, it only worked 1/5 times anyhow). Hold tight while I try to get it back online.

It's not a great way to view them, but they all exist here:

https://github.com/maykar/custom-header/tree/docs/docs

**Comment by maykar** [comment]
Back online
