### ISSUE TITLE
Browser refresh takes you back to default tab

### ISSUE THREAD

**Issue by wbilger** [maykar/custom-header#56]
HASS: v0.103.2
CC: v1.1.0

As title says, when browser is refreshed you are taken back to default tab. 
The actual page is refreshed, but then after it loads, you are then take to default tab.
Not sure if this is by design, but even if homesetter is used, or on Fully Kiosk browser where a different page is used as home screen for dashboard, it goes back to default tab.

**Comment by maykar** [comment]
Please, try latest (1.1.2) and let me know how it goes.

**Comment by wbilger** [comment]
Works great now, thanks.

**Comment by maykar** [comment]
This "fix" was causing issues in some browsers and is now a configurable option, but it is off by default. Add `default_tab_on_refresh: true` to turn it on.

**Comment by maykar** [comment]
Fixed in latest release and docs, but the above comment should read:

This "fix" was causing issues in some browsers and is now a configurable option, but it is ON by default. Add default_tab_on_refresh: false to turn it off.

had it backwards before.
