### ISSUE TITLE
Icons and text on tabs

### ISSUE THREAD

**Issue by jankete** [maykar/custom-header#58]
Hi, would it be possible to get icon and text on a tab? Now we have only a choice between icon or text.

Tanks :-)

**Comment by maykar** [comment]
Thinking this would be nice as like an advanced tab feature where you can add an icon and text and both can be templated. The only issue is the tab would have to begin as text only as there are strange bugs with the selection indicator if an icon is used initially.

**Comment by codeclinic** [comment]
I've no idea what the bug is but could this be overcome by using css to switch the icon and text around?

**Comment by maykar** [comment]
The bug has to do with active tab styling and the indicator size and there are a few ways that I can work around it. The best one would be to rewrite how I'm building the tabs/views. This is a feature that is high on my list, but I'm not sure when I might get to it.

**Comment by fti7** [comment]
Any news here? That would be really a great feature :-) also with the "Icon" Only mode for small devices

**Comment by LordShadowen** [comment]
+1 
Most wanted feature for me as well....

**Comment by maykar** [comment]
This feature is a priority for me, I've been messing with it for a while now. This will need to also include a way to change the tab's text based on templates, so it's in line with other CH features. Thanks for your patience and I hope to get this in soon.

**Comment by maykar** [comment]
[Added in 1.5.3](https://community.home-assistant.io/t/custom-header/155399/841)

**Comment by maykar** [comment]
As far as making icon only mode for mobile devices, just use an exception to turn off the feature when on mobile:

```
custom_header:
  tab_icons_and_text: true
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        tab_icons_and_text: false
```

**Comment by LordShadowen** [comment]
I've updated to try it out.
But I'm getting a weird behavior:
- if compact_mode: false, then it only ever shows the icon, regardless of the value of tab_icons_and_text.
- if compact_mode: true, then it always shows BOTH the icon and text, even if tab_icons_and_text is false.

**Comment by maykar** [comment]
Give the latest a try ( 1.5.7 )

**Comment by LordShadowen** [comment]
It seems to be working! Awesome 👍 

One question: what would be the recommended approach to *only* have tab text on standard (non-mobile) devices? 
In other words, right now it seems the default way is to define both (and have them both shown by default) and then use tab_icons_and_text: false on an exception. But there is no flag to disable icon only, even I made an exception for non-mobile devices. 

Maybe using tab_icons with "none" on an exception? What do you recommend?

**Comment by maykar** [comment]
Using tab_icons would be a bit of a pain as that option doesn't take ranges, but I have a bit of a hack for you.

Use this to hide all tab icons:

`header_text: '<style>ha-icon{display:none;}<style>'`

**Comment by maykar** [comment]
```
  header_text: >-
    <style>ch-header ha-icon{display:none;margin:0;}ch-footer
    ha-icon{display:none;margin:0;}<style>
```

**Comment by LordShadowen** [comment]
do you mean header_text or header_text_css?
header_text actually works, but only if compact_mode: false (and deletes the title string in the process...). But if compact_mode: true it doesn't seem to be processed, so no styling

**Comment by maykar** [comment]
I meant header_text, but yeah if you're using compact mode then it would be disabled. But you can put this into any text option really. It's just a side effect of how the text is inserted, you can hide html inside to do some fairly interesting things.

Since you're using compact mode I would just do something like the following example. Start it off with the name of the actual tab, but sneak the code in after. So, in the example below the name of the tab would be "TabName" and the code would still function.

```
  tab_text:
    0: >-
      TabName<style>ch-header ha-icon{display:none;}ch-footer
      ha-icon{display:none;}</style>
```

If you make a feature request for an icon and text only mode then I won't forget to try to put one in the next release.

**Comment by LordShadowen** [comment]
Created.

In the meantime, I see how the hack works, but wouldn't it require an exception to redefine the tab name when we do want the icon?
Otherwise the icon would be always hidden...

**Comment by maykar** [comment]
Yup, the hack will hide ALL tab icons, not just the one used in the config option. So this would mean that instead of having to set every icon to 'none' you can use the code above in either the default config or an exception and this code in the opposite spot:

```
  tab_text:
    0: TabName
```

**Comment by LordShadowen** [comment]
Works great - awesome work 👍
