### ISSUE TITLE
Tab icons only work one way

### ISSUE THREAD

**Issue by PaulAntonDeen** [maykar/custom-header#62]
This is my config:
```
custom_header:
  tab_icons:
    Actieve lampen: >-
      {% if is_state("group.all_lights", "on") %} mdi:lightbulb-on {% else
      %}mdi:lightbulb-off-outline{% endif %}
  compact_mode: true
```

The goal is that when the last light switches off, the icon becomes an empty light bulb. When at least one of the lights in the group is on, the icon is a full lightbulb. This used to work well in CCH with this code:
```
cch:
  conditional_styles:
    template:
      - tab:
          Actieve lampen:
            - icon: >
                if (states["group.all_lights"].state == "on")
                "mdi:lightbulb-on"; else "mdi:lightbulb-off-outline";`
```

The problem is that on load my frontend loads the standard icon (not the one defined here) and it only changes once when I go from lights on -> lights.off then it becomes the correct icon and never changes back.
The if statement renders correctly in the development tools -> template test page on Hassio.

Any errors relevant to Custom Header found in the HA logs: none
Any relevant errors found in your browsers dev console (usually found by hitting F12): none
The version of Home Assistant and Custom Header you are using: 103.3 
The browser type your are using: chrome on mac and android

**Comment by maykar** [comment]
That's because there are extra spaces in your config. The test template will show you that as well. When your lights are on your template returns " mdi:lightbulb-on ". Notice the space before and after.

In Jinja you can add a dash after and before each % to strip whitespace to fix this problem:
```
    Actieve lampen: >-
      {%- if is_state("group.all_lights", "on") -%} mdi:lightbulb-on {%- else
      -%}mdi:lightbulb-off-outline{%- endif -%}
```

Or simply use the same config that you have, but remove the extra spaces:
```
    Actieve lampen: >-
      {% if is_state("group.all_lights", "on") %}mdi:lightbulb-on{% else
      %}mdi:lightbulb-off-outline{% endif %}
```

**Comment by PaulAntonDeen** [comment]
You are absolutely right, sorry for wasting your time, thanks!

**Comment by maykar** [comment]
Also, if by default the tab is setup to use `mdi:lightbulb-off-outline` you could just use this as Custom Header will use the default tabs Icon if none is set.

`    Actieve lampen: '{% if is_state("group.all_lights", "on") %}mdi:lightbulb-on{% endif %}'`
