### ISSUE TITLE
Shadow on scroll

### ISSUE THREAD

**Issue by jmart518** [maykar/custom-header#63]
Noticed that with Custom Header enabled, the header drop shadow on scroll no longer works (see screen shots)

Without CH enabled:
<img width="348" alt="Screen Shot 2019-12-22 at 3 54 53 PM" src="https://user-images.githubusercontent.com/1509640/71328376-95e91000-24d3-11ea-9afc-b47bff607bb3.png">

With CH enabled:
<img width="246" alt="Screen Shot 2019-12-22 at 3 55 49 PM" src="https://user-images.githubusercontent.com/1509640/71328377-997c9700-24d3-11ea-8f70-01c540820bf1.png">

**Comment by maykar** [comment]
Added in the latest version 1.1.4, can be toggled with `shadow: false`

**Comment by jmart518** [comment]
Thanks for getting this resolved so quickly!  Very minor, but the default behavior of the stock header is flat/no shadow until you scroll and then it "lifts" up (nice animation) to allow the page to flow under it.

Not sure if this is something that Custom Header can replicate or not

**Comment by maykar** [comment]
That's how it should be working when in normal mode or compact mode, should fade in after scrolling a bit. When using footer mode or split mode shadows will always be enabled to keep it consistent, since the bottom portion could already be covering a card.

**Comment by jmart518** [comment]
Shoot, I'm sorry about that, I had styling as a work around (box shadow on the header)

I removed that and no longer have the shadow, however I'm also not getting it on scroll.  I tried clearing cache and Incognito.

Is there anything besides adding:
`shadow: true`

**Comment by maykar** [comment]
Nope, that's all you should need. In fact since shadow is true by default you shouldn't even need `shadow: true`. Will look into it more when I can.

**Comment by maykar** [comment]
From my test HA instance:

![shadow](https://user-images.githubusercontent.com/25127328/71418483-ae266f80-2638-11ea-8063-0dbf092ede46.gif)

**Comment by maykar** [comment]
From my test HA instance:

![shadow](https://user-images.githubusercontent.com/25127328/71418559-06f60800-2639-11ea-8df7-eec835bc3d76.gif)

**Comment by maykar** [comment]
What browser are you using?
Any errors in your dev console (F12)?
What version of Custom Header is reported in the dev console?

**Comment by jmart518** [comment]
Chrome 79 (MacOS)
No errors
Hmm it's showing v1.1.3 but HACS shows v1.1.4

**Comment by jmart518** [comment]
Uninstalled and reinstalled CH, 1.1.4 is now showing in dev panel and shadow is working great.

Thank you!

**Comment by jmart518** [comment]
Looks like this issue cropped again with the latest release

**Comment by maykar** [comment]
Is your config the same as it was? This is on current version:

![shadow](https://user-images.githubusercontent.com/25127328/78060878-4e87e080-735a-11ea-9906-d4672a0b0f06.gif)

**Comment by maykar** [comment]
Is your config the same as it was? This is on current version:

![shadow2](https://user-images.githubusercontent.com/25127328/78061205-d968db00-735a-11ea-855d-5661f2d9f831.gif)

Gif isn't great, but shadow is working.

**Comment by jmart518** [comment]
Hey Ryan,

Config is basically the same, except on mobile I have a bottom header.

Here's how it looks on mine since updating:
[image: Screen Shot 2020-03-31 at 12.50.44.png]

Anything change from: shadow: true

**Comment by maykar** [comment]
No change in config, everything should be the same. Can't see your screenshot for some reason. Could you also share your full config?

**Comment by jmart518** [comment]
compact_mode: true
hide_help: true
shadow: true
exceptions:
- conditions:
user: 'JT Martinez'
config:
button_text:
options: "{{states('sensor.time')}}"
hide_config: true
hide_tabs:
- 7
- conditions:
user: 'JT Martinez'
#user_agent: Mobile
media_query: "(max-width: 600px)"
config:
button_text:
options: "{{states('sensor.time')}}"
clock_format: 24
hide_config: true
hide_unused: true
footer_mode: true
indicator_top: true
default_tab: 0
hide_tabs:
- 1
- 2
tab_container_css: 'padding-left: 68px'
tabs_css:
3: 'margin-left: 8px'
4: 'margin-left: 8px'
- conditions:
user: 'Kendra Martinez'
user_agent: Mobile
config:
options: show
hide_config: true
hide_unused: true
footer_mode: true
indicator_top: true
default_tab: 0
hide_tabs:
- 1
- 2
- conditions:
query_string: kiosk
config:
kiosk_mode: true

**Comment by jmart518** [comment]
`
  compact_mode: true
  hide_help: true
  shadow: true
  exceptions:
    - conditions:
        user: 'me'
      config:
        button_text:
          options: "{{states('sensor.time')}}"
        hide_config: true
        hide_tabs:
          - 7
    - conditions:
        user: 'me'
        #user_agent: Mobile
        media_query: "(max-width: 600px)"
      config:
        button_text:
          options: "{{states('sensor.time')}}"
        clock_format: 24
        hide_config: true
        hide_unused: true
        footer_mode: true
        indicator_top: true
        default_tab: 0
        hide_tabs:
          - 1
          - 2
        tab_container_css: 'padding-left: 68px'
        tabs_css:
          3: 'margin-left: 8px'
          4: 'margin-left: 8px'
    - conditions:
        user: her'
        user_agent: Mobile
      config:
        options: show
        hide_config: true
        hide_unused: true
        footer_mode: true
        indicator_top: true
        default_tab: 0
        hide_tabs:
          - 1
          - 2
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true`

**Comment by maykar** [comment]
I had changed how the header is build and now shadow isn't currently set on compact mode. Will have this fixed in the next release, thank you!

**Comment by jmart518** [comment]
Awesome, thank you!
