### ISSUE TITLE
Cannot upgrade / install

### ISSUE THREAD

**Issue by mf-social** [maykar/custom-header#64]
May well be a HACS issue, but all my other HACS-installed things are updating fine - trying to update this one gives me the following two errors in the log....

```
2019-12-23 11:34:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140415940246992] Unable to serialize to JSON: Object of type AIOGitHubException is not JSON serializable
{'id': 34, 'type': 'event', 'event': {'event_type': 'hacs/error', 'data': {'message': AIOGitHubException('GitHub returned 404 for https://api.github.com/repos/maykar/custom-header/contents/dist')}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 12, 23, 11, 34, 41, 637859, tzinfo=<UTC>), 'context': {'id': 'f2bedc745d1f4232a71bd3730ccddb48', 'parent_id': None, 'user_id': None}}}
2019-12-23 11:34:58 ERROR (MainThread) [hacs.repository.plugin.maykar.custom-header] Download was not complete.
```

😢

**Comment by mf-social** [comment]
Manually deleting the custom-header folder from www , restarting homeassistant and installing afresh from HACS allowed it to be installed, but I will leave this open in case it means anything to you?

**Comment by ludeeus** [comment]
Restart HA and it should/will work.
If that fails, uninstall then install again.
The issue is that custom-header moved from beeing located under /dist, to be on the release pages instead.

**Comment by maykar** [comment]
Added a pinned issue for this
