### ISSUE TITLE
Changing theme doesn't change colors

### ISSUE THREAD

**Issue by dwainscheeren** [maykar/custom-header#66]
When changing my HA theme it doesn't directly change the custom header colors. Only after a page refresh.

Using the latest version of custom header and HA. And my theme color values for example:
````yaml
ch-background: '#121314'
ch-active-tab-color: '#307aff'
ch-all-tabs-color: '#ffffff'

**Comment by maykar** [comment]
Should be fixed in the latest version 1.1.4

**Comment by dwainscheeren** [comment]
This bus does stil exists, in the latest version!

**Comment by dwainscheeren** [comment]
@maykar
