### ISSUE TITLE
Swipe left and right 

### ISSUE THREAD

**Issue by broyuken** [maykar/custom-header#69]
Since the old add on CCH was deprecated I’m now using this one and it’s great, the only thing I’m missing is the ability to swipe left and right between views. Can we get that added back please?

**Comment by maykar** [comment]
This has already been addressed at the [top of the issues page](https://github.com/maykar/custom-header/issues) here on GitHub, the [important notes section](https://maykar.github.io/custom-header/#intro/notes) of the docs, and in quite a few posts on the forums.

Swipe navigation and Custom Header will remain seperate

**Comment by broyuken** [comment]
Sorry, I completely failed to search this time, I just posted too quickly from my mobile. Apologies and thanks for all your hard work.
