### ISSUE TITLE
In panel view picture scrolls under the header.

### ISSUE THREAD

**Issue by KarolisKirna** [maykar/custom-header#70]
With standard header that's not the case. When using CH it starts to happen.
Before scrolling:
![image](https://user-images.githubusercontent.com/23739468/71489941-f1e3c980-2830-11ea-81f6-9a0383b4add6.png)
After scrolling:
![image](https://user-images.githubusercontent.com/23739468/71490003-40916380-2831-11ea-90f9-7051d9662560.png)

**Comment by maykar** [comment]
Try the latest release and see if it helps 1.1.6

**Comment by KarolisKirna** [comment]
With version 1.1.6 everything works as expected. This thing was driving me crazy ... Big thank you @maykar !!!
