### ISSUE TITLE
can't see unused entities 

### ISSUE THREAD

**Issue by adonno** [maykar/custom-header#71]
I am currently unable to see the unused entities in the menu even though it isn't hidden 
![Screen Shot 12-28-19 at 06 35 PM 001](https://user-images.githubusercontent.com/13216947/71549092-fa1a4100-29b7-11ea-8a74-ee6fe8b45700.PNG)
![Screen Shot 12-28-19 at 06 35 PM](https://user-images.githubusercontent.com/13216947/71549093-fa1a4100-29b7-11ea-9fa3-928774e93376.PNG)

**Comment by maykar** [comment]
Unused entities doesn't exist in the menu from your screenshot. After you hit "configure ui" it will then show up in that menu.

**Comment by adonno** [comment]
yes, correct but why isn't it showing in the first menu? (just wondering )

**Comment by maykar** [comment]
That was a change in Home Assistant at some point, has nothing to do with Custom Header.
