### ISSUE TITLE
Doesn't work in wallpanel android app

### ISSUE THREAD

**Issue by notz** [maykar/custom-header#76]
It works in all of my browser but doesn't show up in wallpanel android app on my tablet. The old cch plugin worked fine.

![Screenshot_20200101-112733](https://user-images.githubusercontent.com/697251/71761304-8e5d3a00-2ec9-11ea-8f15-5c1b2b908da2.png)

**Comment by maykar** [comment]
Please, read issues section. You can find the link in the comment above this one. Provide as much of the requested information as you can. I'm especially interested in if there are errors and what they might be, but anything more than the fact that it isn't working would be helpful.

**Comment by maykar** [comment]
Feel free to keep this thread going, but for now I'm closing as stale. Try the latest release.
