### ISSUE TITLE
Per view/tab exceptions

### ISSUE THREAD

**Issue by jimz011** [maykar/custom-header#82]
Hi @mayker as always great work. The new custom header is a lot more stable than the old one.

I do have a request though. Would it be possible to have different configs per view? Say on the frontpage (view 0) we can put a marquee, but on the first view (view 1) have something else? Same applies to buttons for example so I can show a menu button on the frontpage and a home button on the other views?

Also would it be possible to make buttons do a service call instead of navigation? (Srry didn’t see if this is already possible).

Anyways a big thanks once again. And a great 2020 to you!

Jimz011

**Comment by maykar** [comment]
`Would it be possible to have different configs per view? `
I'm looking into this, trying to find the best way to handle it without glitches.

`Also would it be possible to make buttons do a service call instead of navigation?`
I don't think this is something that I would add, unfortunately.

**Comment by jimz011** [comment]
No problem, it was just a question. I can make separate configs using exceptions But it seems a bit hacky though. But thanks for your reply.

Last question, If I split the header I can have text in the top and buttons below. Would it be possible to have text and a few buttons? Like in the screenshot? This would be in the header text area. As I want a separate footer with other buttons.

![1DFBF97A-9306-4B1B-BDD5-C94B5729469C](https://user-images.githubusercontent.com/47046878/71917925-86c7ba80-3181-11ea-953c-5b3b4bcb23ce.png)

**Comment by maykar** [comment]
It's possible with a template in the header text, some creative html/css to create your own buttons, and probably a couple of divs with one justified left (header text) and one right (buttons). All I can say is check out the existing templates on the [showcase thread](https://community.home-assistant.io/t/custom-header-template-showcase-and-discussion) as a start.

**Comment by maykar** [comment]
This has been added or fixed in the [latest version 1.2.2](https://community.home-assistant.io/t/custom-header/155399/367). After updating be sure to check your browser's dev console (usually F12) to make sure you are running the latest version. If it doesn't display 1.2.2 you may either need to clear your cache or reinstall.
