### ISSUE TITLE
Option to remove menu arrows

### ISSUE THREAD

**Issue by barrymossel** [maykar/custom-header#84]
Option to remove arrows below:

![Screenshot_20200106-191727_Chrome_2](https://user-images.githubusercontent.com/10389401/71838856-186bf500-30ba-11ea-9ba5-f562c2cc1786.jpg)

**Comment by maykar** [comment]
https://maykar.github.io/custom-header/#configuration/tabs

`chevrons: false`

**Comment by barrymossel** [comment]
Just found it, thanks. But still would be nice to have the option in the UI.

**Comment by maykar** [comment]
It is in the UI

**Comment by maykar** [comment]
![image](https://user-images.githubusercontent.com/25127328/71840464-5d2c6780-308b-11ea-964d-e2edbcfd89f6.png)

**Comment by barrymossel** [comment]
Wow, thanks. I guess I am blind (and never heard of the word chevrons) ;)
