### ISSUE TITLE
Is it possible to style a template variable? 

### ISSUE THREAD

**Issue by rpitera** [maykar/custom-header#86]
I'm really loving the template variables and finding them truly useful!

I'd like to change the background and font color of a templated variable, is this possible?

If not, could this be considered as a feature request?  Thanks!

**Comment by maykar** [comment]
Styling templates can be done with a bit of css or html. You can look to the [template showcase thread](https://community.home-assistant.io/t/custom-header-template-showcase-and-discussion) for inspiration or even the [custom css options](https://maykar.github.io/custom-header/#styling/advanced). These aren't really supported features and will take trial and error to get the result you want.

**Comment by rpitera** [comment]
Thanks, Ryan!
