### ISSUE TITLE
Applying settings after page error and page reload

### ISSUE THREAD

**Issue by ercsey** [maykar/custom-header#88]
I don't now if it's an error, a bug and I don't know even if it's the custom-header fault or not so sorry if it's false alarm.

I'm using Hass.io on an Intel NUC with Ubuntu on docker. 
HA version 0.103.6
Custom Header version 1.1.7
The problem occurs on different browsers: Chrome, Firefox, Fully Kiosk Browser.

Settings:
custom_header:
  compact_mode: true
  voice_hide: true
  options_hide: false
  default_tab: 0
  hide_tabs: 
    - 2
  exceptions:
    - conditions:
        user: Tablet
      config:
        kiosk_mode: true
        default_tab: 1
        hide_tabs: 
          - 0
          - 2

Description:
Basically on a page error (I have a camera stream and when the camera disconnects the page gets an error, but not only on camera error.) in developer tools I see this log:

> connection-mixin.ts:82 Uncaught (in promise) {type: "result", success: false, error: {…}}
> callService @ connection-mixin.ts:82
> async function (async)
> callService @ connection-mixin.ts:57
> e.callService @ browser_mod.js:56
> Et @ button-card.js:801
> _handleTap @ button-card.js:1720
> handleEvent @ button-card.js:243
> N.__boundHandleEvent @ button-card.js:232
> n  @ button-card.js:824

As a result the Custom Header not reloads correctly the header. (see attached file. Sorry for the cut out... sensitive information.)
![Screenshot 2020-01-08 20 07 02](https://user-images.githubusercontent.com/11696531/72004914-125e4b80-3255-11ea-8d01-48327e9f399a.png)

**Comment by maykar** [comment]
None of these errors are related to Custom Header and I wouldn't know where to even begin trying to troubleshoot this. There are many errors related to card-mod, button-card, and even one for browser-mod in there. Maybe those would be good places to start?

**Comment by maykar** [comment]
A good way to see if Custom Header has anything to do with this would be to temporarily remove Custom Header from your resources and see if anything changes, as is mentioned in the [issues section](https://maykar.github.io/custom-header/#issues) of the docs.

**Comment by ercsey** [comment]
Thank you. I will try to reduce the possibility of errors and inform you if it's Custom Header related.
