### ISSUE TITLE
Docs site Safari issues

### ISSUE THREAD

**Issue by alderete** [maykar/custom-header#89]
The documentation site for custom-header, https://maykar.github.io/custom-header/, doesn't work in Safari on macOS (Safari 13.0.4, macOS 10.14.6 "Mojave"). The navigation links in the left sidebar (Installation, Configuration, and so on) do nothing.

The design of the site is cute, but the docs won't do anyone any good if you can't actually get to them.

**Comment by alderete** [comment]
FWIW, the site **does** work in Google Chrome (latest) on macOS.

Feels like 1997 all over again.

![best-with-ie](https://user-images.githubusercontent.com/4359/72038126-3de13600-3255-11ea-91d0-7d158dd2a6b6.png)

**Comment by maykar** [comment]
Safari has multiple issues with the site currently. Since almost any other browser works fine it's low on my priorities at the moment, but it is on my radar.

**Comment by maykar** [comment]
Fixed
