### ISSUE TITLE
Templating Variable: view_title

### ISSUE THREAD

**Issue by xMrVizzy** [maykar/custom-header#91]
Hello! A new variable is needed to make each tab show their default view name in header_text! I seen that you use: custom-card-helpers, And I think it would be easy to add that! 

Now to make the display in the header_text - the name of the tab, I had to create my own card that when opening a certain tab call service to select option in input_select with the name of the tab and then through templating sets in header_text!

It would be easier to specify: header_text: "{{ view_title }}"

My example of using this:
Home page
<img width="506" alt="CleanShot 2020-01-10 at 05 26 45@2x" src="https://user-images.githubusercontent.com/7906418/72115713-d072f980-3369-11ea-8da8-a5d7bd80ddbf.png">

Lights page
<img width="505" alt="CleanShot 2020-01-10 at 05 27 20@2x" src="https://user-images.githubusercontent.com/7906418/72115740-e41e6000-3369-11ea-9ee2-2474beae1a58.png">

And also I use different show_tab for each page based on view title!

<img width="610" alt="CleanShot 2020-01-10 at 05 28 20@2x" src="https://user-images.githubusercontent.com/7906418/72115795-07e1a600-336a-11ea-9638-c78a70fa4f66.png">

**Comment by maykar** [comment]
This would require rendering of templates on every tab change and I'm not sure I would add something like this as it would cause other things to look glitchy.

If I do manage to get something like per tab config (#82) working without bugs and glitches I will think about something like this.

**Comment by maykar** [comment]
I'll keep this open in case that actually works out.

**Comment by maykar** [comment]
This has been added or fixed in the [latest version 1.2.2](https://community.home-assistant.io/t/custom-header/155399/367). After updating be sure to check your browser's dev console (usually F12) to make sure you are running the latest version. If it doesn't display 1.2.2 you may either need to clear your cache or reinstall.

**Comment by xMrVizzy** [comment]
Awesome, thank you!
