### ISSUE TITLE
Feature request: The position of the tabs

### ISSUE THREAD

**Issue by xMrVizzy** [maykar/custom-header#92]
Now when using show_tabs, the tab order is used in the order in which the tab files or tabs are added to the ui-lovelace!

It would be great if you could use some option to be able to set the tabs in own order!

Now if I set this  -  show_tabs: "3, 2, home", anyway it order like "home, 2, 3"

**Comment by maykar** [comment]
I don't think this is something I will add, this was mentioned in this feature request as well #85
