### ISSUE TITLE
Exception config for hiding specific sidebar icons

### ISSUE THREAD

**Issue by bruxy70** [maykar/custom-header#95]
It would be nice if I can hide selected icons on the sidebar in exception config, similar to how I can hide tabs today.
I can see two use cases
 - to hide some tools to specific users - as the sidebar can contain a mix of admin tools and user tools (such as map, notification, user profile, maybe some others)
 - to hide tools that are useless on mobile device
Today, the only option is to disable the whole sidebar - but then people can't even change their password.
Thanks!

**Comment by maykar** [comment]
I won't be adding any features related to the sidebar. Since CH only operates inside of Lovelace I need to keep any interaction with the sidebar to a minimum. The sidebar is required for navigation outside of Lovelace, so any modification of it should be handled with an addon that is available across the entire frontend.

**Comment by bruxy70** [comment]
Ok, will look in there or write one. Can you please point me into the right direction?
Integrations are backend things, they do not run in the context of individual user sessions.
Python scripts and Appdaemon scripts the same.
Then there are plugins, are frontend customization, so they seem to be the way to go - but you say they run only for lovelace.
Then there is the addon store, but that is only for hass.io (and I am not even sure how wold that work).
Do you know any such addon you mention?
Thanks

**Comment by maykar** [comment]
So this would need to be added as an extra_module, I have yet to look into creating one myself, but you'd add custom JS by using extra_module_url in your config. Something like:

```
frontend:
  extra_module_url:
    - /local/NameOfScript.js
```

https://www.home-assistant.io/integrations/frontend/#extra_module_url

**Comment by maykar** [comment]
I've been toying with the idea of a Custom Sidebar addon like this for a while, but just haven't had the time to get into it. If you do end up making something like this, please let me know as I have some code that I scrapped from an earlier version of Custom Header you might be interested in. It allows the sidebar to be moved to the right side of the screen, but for the reasons mentioned above I kept it out of Custom Header.

**Comment by maykar** [comment]
Was looking for this, but finally found the addon that uses this method:

https://github.com/andrey-git/home-assistant-custom-ui

**Comment by bruxy70** [comment]
Thanks :)
