### ISSUE TITLE
button_text issue

### ISSUE THREAD

**Issue by avehome** [maykar/custom-header#96]
Hi @maykar,

I just updated CH to the latest version and see a dot before the date?
Dot is produced by {{ monthNameShort }}.

The code:
![image](https://user-images.githubusercontent.com/50752001/72211410-2d39f580-34cb-11ea-83c4-c6c1a1ccc235.png)

Preview:
![image](https://user-images.githubusercontent.com/50752001/72211233-03cb9a80-34c8-11ea-98bf-01c61eaf55c4.png)

Greetings from The Netherlands

**Comment by maykar** [comment]
Please, try the latest release 1.2.1 and report back if the issue persists or close the issue if it has been solved.

**Comment by avehome** [comment]
Still the same in the latest release 1.2.1

**Comment by maykar** [comment]
Can you confirm in your browser's dev tools console (F12) that the correct version of Custom Header is reported (1.2.1). I ask because using your same config I get this:

![image](https://user-images.githubusercontent.com/25127328/72304330-3e574380-363e-11ea-841c-3791645e5345.png)

**Comment by maykar** [comment]
Please see this comment and the following 2:

https://community.home-assistant.io/t/custom-header/155399/341

Seems there have been some issues when updating in HACS and it actually wasn't updating. Double check that you are on 1.2.1 and reinstall in HACS either way.

**Comment by maykar** [comment]
Going to close this one as there have been multiple reports of this just being a HACS/cache issue.
