### ISSUE TITLE
Bring back swipe mode

### ISSUE THREAD

**Issue by GuitarSkater** [maykar/custom-header#98]
I love all the new changes and guides with the new version. Am I missing something or is swipe through lovelace tabs no longer a thing?

**Comment by maykar** [comment]
Please, read the [pinned issue](https://github.com/maykar/custom-header/issues) at the top of the issues page or the [important notes](https://maykar.github.io/custom-header/#intro/notes) in the docs

**Comment by GuitarSkater** [comment]
Thank you, I clearly overlooked it
